Content.Shared/CCVar/CCVars.cs
Поменял значение Cvar. Теперь при нажатии кнопка шифт игрок будет идти пешком.
---
:cl: Spatison
- tweak: Press to walk / Нажать чтобы идти
=> [Tweak] Press To Walk / Нажать Чтобы Идти

Resources/Locale/en-US/tools/tool-qualities.ftl, Resources/Prototypes/Entities/Objects/Weapons/Melee/fireaxe.yml, Resources/Prototypes/Tiles/plating.yml, Resources/Prototypes/_White/tool_qualities.yml, Resources/Prototypes/tool_qualities.yml
Advanced prying для снятия плитки топором
:cl: Warete
- add: The ability to remove tiles with axes / Возможность снимать плитку топорами
=> [Port] Advanced Prying

Content.Server/Administration/Commands/AdminWhoCommand.cs
Команду adminwho теперь могут использовать все игроки
---
:cl: Spatison
- tweak: An ordinary player can now use adminwho / Обычные игроки теперь могут использовать adminwho
=> [Tweak] Adminwho

Content.Server/Disposal/Unit/EntitySystems/DisposalUnitSystem.cs
Убран промах у мусорки. Теперь всегда будет гол! / The miss by the trash can has been cleaned up. Now there will always be a goal!
---
:cl: TokiJumper
- remove: You can no longer miss when throwing something in disposal bin / Убран промах у мусорки.
=> [FIX] Промах у мусорки

Resources/Locale/ru-RU/_white/emotes/speech-emotes.ftl
=> [Fix] Emotion / Эмоции

Content.Client/Lobby/UI/LobbyGui.xaml
Исправлен баг с размером элементов лобби
---
:cl: Spatison
- fix: The size of the Lobby cannot be changed now / Размер лобби теперь нельзя изменить
=> [Fix] Lobby / Лобби

README.md
It looks like this is your first time opening a pull request in this project!
Reporting a security vulnerability?
Check out the project's [security policy](https://github.com/WWhiteDreamProject/wwdpublic/security/policy).
=> Change logo in the readme

Resources/Prototypes/Entities/Mobs/Species/dwarf.yml
Изменен вес дварфоф с 32 -> 71
---
:cl: Spatison
- tweak: Dwarf now weigh more / Дварфы теперь весят больше
=> [Tweak] Dwarf's Weight / Вес Дварфов

Resources/Prototypes/Entities/Objects/Misc/subdermal_implants.yml, Resources/Prototypes/_White/Store/presets.yml
Порт импланта нейро стабильности и небольшой рефактор имплантов для майндслейва.
---
:cl: Spatison
- fix: No more discounts in uplink implant / Больше никаких скидок в имплант аплинка
=> [Fix] No Discounts In Uplink Implant / Никаких Скидок В Импланте Аплинка

Resources/Prototypes/secret_weights.yml
Изменены шансы режимов. Каждый второй раунд не будет запускаться с выживания
---
:cl: Spatison
- tweak: Changed the chances of secret modes / Изменены шансы режимов в секрете
=> [Tweak] Secret / Секрет

Resources/Prototypes/GameRules/midround.yml
Зачем его вообще добавили?
---
:cl: Spatison
- remove: Thieves' pacifism has been removed / Убран воровской пацифизм
=> [Remove] Thieves' Pacifism / Воровской Пацифизм

Content.Shared/Projectiles/EmbeddableProjectileComponent.cs, Content.Shared/Projectiles/SharedProjectileSystem.cs, Content.Shared/Throwing/ThrownItemSystem.cs, Resources/Prototypes/Entities/Objects/Fun/darts.yml, Resources/Prototypes/Entities/Objects/Materials/shards.yml, Resources/Prototypes/Entities/Objects/Misc/tiles.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/spear.yml, Resources/Prototypes/_White/Entities/Objects/Weapons/Melee/spear.yml
Исправление колизии у осколка стекла
---
:cl: Spatison
- fix: correction of a collision at a glass shard/ Исправление колизии у осколка стекла
=> [Fix] Fixture / Колизия

Resources/Prototypes/_White/Research/experimental.yml
ftl -> yml.
---
:cl: Spatison
- fix: ПНВ и ПТВ теперь могут быть исследованы /  NVG and TVG can now be researched
=> [Fix] Research / Исследования 

Content.Shared/CCVar/CCVars.cs
Добавлена ссылка на вики в меню игры.
---
:cl: TokiJumper
- add: Added link to wiki in EscMenu/Добавлена ссылка на вики в меню игры
=> Added link to wiki in EscMenu

Resources/Prototypes/Catalog/VendingMachines/Inventories/cargodrobe.yml, Resources/Prototypes/Catalog/VendingMachines/Inventories/detdrobe.yml, Resources/Prototypes/Catalog/VendingMachines/Inventories/dinnerware.yml, Resources/Prototypes/Catalog/VendingMachines/Inventories/robodrobe.yml, Resources/Prototypes/Catalog/VendingMachines/Inventories/salvage.yml, Resources/Prototypes/Catalog/VendingMachines/Inventories/wallmed.yml, Resources/Prototypes/Catalog/VendingMachines/Inventories/youtool.yml
Перенёс старое и добавил новое в инвентари автоматов.
:cl: Warete
- tweak: Vending Machine's inventory update / Обновление инвентаря торг. автоматов
=> [Tweak] Vending Inventory

Resources/Prototypes/Entities/Structures/Machines/metempsychoticMachine.yml
Убрал приколы с клонированием с данного агрегата.
Система кармы не работает, а даже если заработает, под хирургию маловероятно что кто-то её сделает.
:cl: Warete
- tweak: Metempsychotic cloning machine now common cloning machine / Агрегат с труднопроизносимым названием наконец-то работает как обычная машина для клонирования
=> [Tweak] Metempsychotic cloning machine

Resources/Prototypes/Entities/Surgery/surgery_steps.yml
Исправлен неправильно отображающий инструмент для лечения в меню хирургии при залечивании ран
---
<p>
https://discord.com/channels/1274951101464051846/1318609450319478825
</p>
</details>
---
- fix: Surgery step sprite / Спрайт этапа хирургии
=> [Fix] Surgery step sprite

Content.Server/Antag/AntagSelectionSystem.cs, Content.Server/Antag/Components/AntagSelectionComponent.cs, Content.Server/GameTicking/Rules/Components/NukeopsRuleComponent.cs, Resources/Prototypes/Entities/Markers/Spawners/ghost_roles.yml, Resources/Prototypes/GameRules/roundstart.yml
[Порт](https://github.com/space-wizards/space-station-14/pull/28316). 
---
:cl: Spatison
- tweak: Мидраунд ядерные оперативники теперь спавнятся гостами
- tweak: Количество оперативников необходимых для объявление войны: 4 -> 2
- tweak: Количество игроков необходимых для запуска режима ядерных оперативников: 35 -> 20
=> [Tweak] Nuke Ops

Resources/engineCommandPerms.yml
Теперь люди без прав хоста не имеют прав выключить сервер. По просьбе скитузера
---
<p>
</p>
</details>
---
:cl: idoffront
- remove: Отобрано право выключать сервер у малоправных
=> хер вам а не шатдаун

Resources/Changelog/WhiteChangelog.yml
Исправляет неправильно написанный CL - https://github.com/WWhiteDreamProject/wwdpublic/pull/186
---
<p>
</p>
</details>
---
=> [Fix] Warete CL

Resources/Prototypes/_White/Species/resomi.yml
Описание.
---
<p>
</p>
</details>
---
:cl: Oniks
- tweak: Резоми больше нельзя выбрать как игровую расу в редакторе. No fun allowed.
=> [Tweak] Remove round start Resomi

Resources/Prototypes/Catalog/Fills/Boxes/security.yml, Resources/Prototypes/Catalog/Fills/Lockers/security.yml, Resources/Prototypes/Catalog/VendingMachines/Inventories/sec.yml, Resources/Prototypes/Catalog/VendingMachines/Inventories/secdrobe.yml
Изменено наполнение шкафов офицеров СБ:
- Уменьшена рандомизация и блоат
- Бронежилеты ЕЕ заменены на один обычный (старый)
- Добавлены дизейблеры
- Добавлены секхуды
- Спецсредства перенесены в СБтех
- Опции одежды и брони перенесены в Охраншкаф
Коробка очков СБ теперь содержит очки СБ.
---
:cl: vanx
- tweak: Изменено наполнение шкафов СБ; не забывайте про СБТех и Охраншкаф и пользуйтесь опцией лодаутов в настройках персонажа!
=> [Tweak] Security Lockers Reshuffle

Resources/Locale/ru-RU/implant/implant.ftl
=> [Fix] Implant Locale

Resources/Prototypes/NPCs/mob.yml
Моисы больше не руинят игру поварам и королю крыс своим существованием.
На поваре **невозможно играть,** потому-что вечный tower defence на протяжении около 2-х часов раунда - это пиздец. Даже если удалось отбиться, с кухни просто нельзя выйти, потому-что через секунду прибежит свора мышей, которые сразу побегут сжирать всю еду, которую ты наготовил (из-за этого кухня всегда пустая и экипаж питается из автоматов).
На короле крыс **нечего жрать**, кроме пончиков и тех же пары загрифоненых вендингов, просто потому-что до момента его появления мыши сожрали всю еду, заспавненную на карте, или приготовленную поваром.
Одним словом, для такого грифона есть мышь с игроком за рулём и король крыс.
---
<p>
</p>
</details>
---
:cl: PuroSlavKing
- tweak: Изменен …
=> [Tweak] Remove Mouse Spermamassive

Content.Client/Administration/UI/Bwoink/BwoinkControl.xaml.cs, Content.Client/Administration/UI/CustomControls/PlayerListControl.xaml.cs
Черепик [#30518](https://github.com/space-wizards/space-station-14/pull/30518)
---
:cl: Spatison
- fix: Ахелпы должны нормально отображать людей
=> [Fix] AHelp Menu Sorting

Content.Server/Body/Systems/BodySystem.cs, Content.Server/Ghost/GhostReturnToRoundSystem.cs, Content.Server/Ghost/GhostSystem.cs, Resources/Locale/en-US/ghost/ghost-respawn.ftl, Resources/Locale/ru-RU/ghost/ghost-respawn.ftl
Возможный фикс того что призраки умирают через 2 дня после своей смерти
---
:cl: Spatison
- tweak: Время До возможности переродится теперь может показывать секунды, если осталось меньше минуты 
- fix: Время смерти призрака при осмотре теперь показывается правильно
- fix: Время до возрождения теперь не сбрасывается при возвращении в тело
- fix: Время до возрождения теперь должно быть корректным
=> [fix] Ghost Respawn Time

Content.Shared/Humanoid/HumanoidCharacterAppearance.cs, Content.Shared/Preferences/HumanoidCharacterProfile.cs, Resources/Prototypes/Nyanotrasen/Entities/Mobs/Species/felinid.yml, Resources/Prototypes/Nyanotrasen/Species/Oni.yml, Resources/Prototypes/Nyanotrasen/Species/felinid.yml, Resources/Prototypes/Species/arachne.yml, Resources/Prototypes/Species/dwarf.yml, Resources/Prototypes/Species/harpy.yml, Resources/Prototypes/Species/human.yml, Resources/Prototypes/Species/ipc.yml
Больше никаких черных ящеров и невидимых КПБ
---
:cl: Spatison
- fix: The color of the humanoids in the spawn panel is now correct / Цвет гуманойдов в панели спавна теперь правильный
- fix: IPCs can no longer be invisible / КПБ теперь не могут невидимыми
=> [Fix] Humanoid Color

Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Тайтл^
---
:cl: Spatison
- fix: С мышей и тараканов больше не выпадают органы
=> [Fix] No More Organs When Killing A Cockroach

Content.Client/Options/UI/Tabs/MiscTab.xaml, Content.Client/Options/UI/Tabs/MiscTab.xaml.cs, Content.Client/Popups/PopupSystem.cs, Content.Client/UserInterface/Systems/Chat/Widgets/ChatBox.xaml.cs, Content.Shared/_White/CVars.cs, Resources/Locale/en-US/popup/popup.ftl, Resources/Locale/ru-RU/_white/chat/chat-stacking.ftl, Resources/Locale/ru-RU/escape-menu/ui/options-menu.ftl
Выключает засирание чата одинаковыми сообщениями.
---
Самое свежее
[4.webm](https://github.com/user-attachments/assets/0b5f87d5-45aa-4fd2-b377-1097ed75c68f)
<details><summary>Видео постарше</summary>
[1.webm](https://github.com/user-attachments/assets/bc8c3656-0b5f-4319-b02c-beadf9f2c45a)
[2.webm](https://github.com/user-attachments/assets/0e46230e-86b7-4326-9d55-735054d01df8)
[3.webm](https://github.com/user-attachments/assets/3aca45e9-ccba-4955-b4a3-b14054ff9294)
</details>
---
</details>
:cl:
- add: Новая опция в разделе "Общее-Речь" - "Не повторять одинаковые сообщения в чате". По умолчанию включено!
=> Вы указываете на святая ручная граната. x99!

Content.Client/Flight/FlyingVisualizerSystem.cs, Content.Client/Movement/Systems/FloorOcclusionSystem.cs
При полете над водой гарпия не ломает интерфейс 
---
:cl: Spatison
- fix: Теперь при полете над водой гарпия не ломает интерфейс
=> [Fix] Harpy Flight

Resources/Prototypes/Entities/Structures/Decoration/bonfire.yml, Resources/Prototypes/_White/Recipes/Construction/Graphs/structures/bonfire.yml, Resources/Prototypes/_White/Recipes/Construction/bonfire.yml
Крафт костра и костра легиона, йапе.
---
<p>
</p>
</details>
---
=> [Tweak] Craftable Bonfire

Content.Server/Mech/Systems/MechSystem.cs
Действие доставания кого-то из меха теперь сбивается при движении
---
:cl: vanx
- tweak: Действие доставания кого-то из меха теперь сбивается при движении
=> [Twe4k] No Gr4nd Theft Mech

Resources/Locale/ru-RU/deltav/job/job-names.ftl, Resources/Locale/ru-RU/deltav/paper/stamp-component.ftl, Resources/Locale/ru-RU/prototypes/entities/objects/devices/pda.ftl, Resources/Locale/ru-RU/prototypes/entities/objects/misc/identification_cards.ftl
Замена адского ассистента на более благозвучного адъютанта, локализация его кпк и айди
---
:cl: vanx
- tweak: Административный Ассистент переименован в Адъютанта
=> [Tweak] Administrative Assistant -> Адъютант

Resources/Prototypes/Traits/skills.yml
Описание.
Убран аспект на "игнорирование ловушек" который по факту позволял отключить мозг и с начала раунда за бесплатно игнорировать целую основную механику игры - подскальзывание. Повышение цены на этот трейт привело бы только к большему кринжу, и даже взамен на отрицательные перки он был бы слишком сильный.
---
:cl: vanx
- tweak: Убрана черта персонажа на избегание ловушек и любых подскальзываний
=> [Fix] Free Noslips Removed

Resources/Prototypes/Entities/Objects/Weapons/Melee/home_run_bat.yml
Добавил агентской бите (home run bаt) кнок как у телескопички на 1 секунду при откидывании.
Возможно теперь это не будет пустой тратой 16 ТК.
---
:cl: vanx
- tweak: Бита из аплинка теперь роняет при ударе на 1 секунду.
=> [Twe4k] Homerun B4t Knocks Down On Hit

Resources/Prototypes/Entities/Objects/Weapons/Melee/telescopic_baton.yml
Уменьшил урон телескопички с 12 до 6 (у хармбатона и лома 7), взамен добавил урон по стамине, теперь она кладёт за 4 попадания. Увеличил окно кнока с 1.5 до 2 секунд с раскрытия.
Таким образом телескопичка больше подходит для самообороны и попыток кого-то застанить и остановить.
---
:cl: vanx
- tweak: Телескопическая дубинка теперь роняет в первые две секунды после раскладывания и станит с четырёх ударов.
=> [Twe4k] M4ke Telescopic B4ton Us4ble

Resources/Prototypes/CharacterItemGroups/Jobs/Command/commandUncategorized.yml, Resources/Prototypes/CharacterItemGroups/Jobs/Security/uncategorized.yml, Resources/Prototypes/Loadouts/Jobs/Command/uncategorized.yml, Resources/Prototypes/Loadouts/Jobs/Security/uncategorized.yml
Из лодаутов СБ убраны самозарядный лазерный револьвер и энергомеч.
Из лодаутов командования убран станбатон.
---
:cl: vanx
- remove: Из лодаутов убраны энергомечи и энергоревольверы СБ и станбатоны у командования.
=> [Tweak] Removed fun weapons

Content.Server/Objectives/ObjectivesSystem.cs, Content.Shared/Objectives/Components/ObjectiveComponent.cs, Resources/Locale/en-US/objectives/conditions/glimmer.ftl, Resources/Locale/en-US/objectives/conditions/hijack.ftl, Resources/Locale/en-US/objectives/conditions/kill-head.ftl, Resources/Locale/en-US/objectives/conditions/kill-person.ftl, Resources/Locale/en-US/objectives/conditions/other-traitor-alive.ftl, Resources/Locale/en-US/objectives/conditions/other-traitor-progress.ftl, Resources/Locale/ru-RU/deltav/objectives/conditions/teach-person.ftl, Resources/Locale/ru-RU/objectives/conditions/escape-shuttle-condition.ftl, Resources/Locale/ru-RU/objectives/conditions/glimmer.ftl, Resources/Locale/ru-RU/objectives/conditions/hijack.ftl, Resources/Locale/ru-RU/objectives/conditions/kill-head.ftl, Resources/Locale/ru-RU/objectives/conditions/kill-person.ftl, Resources/Locale/ru-RU/objectives/conditions/other-traitor-alive.ftl, Resources/Locale/ru-RU/objectives/conditions/other-traitor-progress.ftl, Resources/Locale/ru-RU/objectives/conditions/steal-few-items-condition.ftl, Resources/Locale/ru-RU/objectives/conditions/steal.ftl, Resources/Prototypes/DeltaV/Objectives/traitor.yml, Resources/Prototypes/Nyanotrasen/Objectives/traitor.yml, Resources/Prototypes/Objectives/traitor.yml
Локализация целек агентов на русский.
Цель "преподать урок" переписана как "расправиться" с новой иконкой и более понятным описанием.
---
</p>
</details>
---
:cl: vanx
- add: Локализация целей агентов синдиката
=> Tr4itor t4sk loc4liz4tion

Resources/Prototypes/Loadouts/Generic/items.yml
В лоадауты добавлен питомец камень
:cl:
- add: Pet rock is now in the loadouts. / Камень-питомец теперь в лоадаутах.
=> [Feature] Камень в лоадауты

Resources/Prototypes/Recipes/Lathes/mech_parts.yml
Багфикс ошибки с неустановленной ценой Vim Harness 
---
small fix no CL
=> [Fix] Free Vim Harness Recipe

Content.Shared/Cuffs/SharedCuffableSystem.cs
Дальность применения наручников 0.3 -> 1.5
---
:cl: vanx
- fix: Исправлена дальность применения наручников
=> [Fix] Cuff Range Being Extremely Small

Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml, Resources/Prototypes/Entities/Structures/Walls/grille.yml
Болты дисейблеров теперь снова пролетают через решётки и окна.
---
:cl: vanx
- fix: Болты дисейблеров теперь снова пролетают через решётки и окна.
=> [Fix] Fix Disabler Bolt Collision

Content.Server/_Goobstation/Ghostbar/Components/GhostBarPlayerComponent.cs, Content.Server/_Goobstation/Ghostbar/GhostBarSystem.cs
:cl: 3189
- tweak: Вход в гостбар больше не влияет на время до возвращения в раунд
=> [Tweak] Вход в гостбар больше не влияет на время до возвращения в раунд

Resources/Prototypes/Actions/crit.yml
У кнопок сдаться и последние слова теперь 10 секундный кулдаун с момента смерти
---
<p>
</p>
</details>
---
:cl: vanx
- tweak: У кнопок сдаться и последнее слово теперь 10 секундный кулдаун с момента смерти
=> [Tweak] No Instant Giveup

Resources/Prototypes/Entities/Structures/Windows/shuttle.yml
Окна шаттлов теперь снова перекрывают решётки не давая им биться током
---
:cl: vanx
- fix: Окна шаттлов перекрывают решётки не давая им биться током
=> [Fix] Shuttle Windows Not Blocking Grilles Electrocution

Content.Server/Forensics/Components/FingerprintComponent.cs, Content.Server/Forensics/Systems/ForensicPadSystem.cs, Content.Server/Forensics/Systems/ForensicsSystem.cs, Content.Server/StationRecords/Systems/StationRecordsSystem.cs, Content.Shared/Forensics/Events.cs, Resources/Locale/en-US/forensics/forensics.ftl, Resources/Locale/ru-RU/forensics/forensics.ftl, Resources/Prototypes/Entities/Mobs/Player/silicon_base.yml
КПБ теперь оставляют на предметах следы перчаток
---
:cl: vanx
- fix: КПБ теперь оставляют на предметах следы перчаток
=> [Fix] IPCs Not Leaving Glove Marks

Resources/Locale/ru-RU/ghost/ghost-gui.ftl
:cl: 3189
- tweak: Перевод меню призраков
=> перевод гост меню

Resources/Prototypes/DeltaV/Entities/Objects/Fun/toy_guns.yml, Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml, Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/LMGs/lmgs.yml, Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Launchers/launchers.yml, Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Rifles/rifles.yml, Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/SMGs/smgs.yml, Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/pka.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/LMGs/lmgs.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Launchers/launchers.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Rifles/rifles.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/flare_gun.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/baseball_bat.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/chainsaw.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/mining.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/sledgehammer.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/stunprod.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/sword.yml, Resources/Prototypes/Nyanotrasen/Entities/Objects/Weapons/Guns/Snipers/snipers.yml, Resources/Prototypes/_EE/Entities/Objects/Weapons/Guns/SMGs/smgs.yml, Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Lever/lever.yml, Resources/Prototypes/_Lavaland/Entities/Objects/Weapons/Guns/Basic/pka.yml, Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Rifles/rifles.yml, Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Snipers/snipers.yml, Resources/Prototypes/_White/Entities/Objects/Weapons/Guns/launchers.yml
Изменен баланс большинства видов оружия ближнего и дальнего боя в отношении размера инвентаря и скрытности:
Более крупное и мощное оружие (автоматические винтовки, дробовики, лазерные винтовки) теперь сложнее спрятать, большинство из них помещается только в вещмешки или в слоты инвентаря.
Пистолеты остаются неизменными и по-прежнему являются наиболее легко скрываемым оружием дальнего боя.
---
(Поверх нарисованы размеры вещмешка и рюкзака для сравнения)
---
Крупное оружие ближнего боя было изменено, чтобы выглядеть красивее и логичнее, при этом более опасное оружие занимает больше слотов и его сложнее спрятать на себе.
Почему / Баланс
Теперь сложнее спрятать крупное оружие, что делает угрозы более явными и провоцирует взаимодействие с игроками (например, тайдер с рюкзаком, который только …
=> [Tweak] Weapons Resize

Resources/Prototypes/Entities/Mobs/Species/reptilian.yml, Resources/Prototypes/_White/Species/harpy.yml, Resources/Prototypes/_White/Species/human.yml, Resources/Prototypes/_White/Species/reptilian.yml
Я дурачек
---
:cl:
- fix: Lizard people's clothing is now displayed correctly again / Одежда на ящерах вновь отображается нормально
- fix: Character breakage is now prevented / Теперь нельзя сломать себе персонажа
=> [Fix] Some Body Type Bugs

Content.Client/Weapons/Melee/MeleeWeaponSystem.cs, Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs, Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs
Убрана автоатака со всего где её не должно быть.
Кулдаун выстрела после удара оружием сокращён теперь зависит от скорострельности.
Возвращён кулдаун удара после выстрела, теперь бить и стрелять одновременно не получится.
:cl: vanx
- fix: Баги системы ближнего боя
=> [Fix] Melee Bugs

Content.Server/Hands/Systems/HandsSystem.cs, Content.Server/Weapons/Melee/MeleeWeaponSystem.cs, Content.Server/Weapons/Melee/ShovingComponent.cs, Content.Shared/CombatMode/DisarmedEvent.cs, Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs, Content.Shared/_White/CVars.cs
ПКМ со свободной рукой в боевом режиме теперь гарантированно _толкает_ (наносит урон по стамине и отталкивает физически в зависимости от соотношения веса) и поверх этого имеет шанс _обезоружить_ цель.
Урон по стамине от толчка теперь зависит только от соотношения веса персонажей, чтобы показать грубую силу.
В среднем это будет 10 +-4 урона за толчок, то есть:
- Средний человек укладывает среднего человека за 10 толчков.
- Средний человек укладывает среднего фелинида за 6 толчков.
- Средний фелинид укладывает среднего человека за 14 толчков.
Шанс обезоружить теперь зависит только от соотношения стамины и здоровья персонажей, чтобы показать их ловкость вне зависимости от размера и веса.
- Стандартный шанс обезоружить между двумя персонажами с полным здоровьем и стаминой = 25%.
- Шанс …
=> [Tweak] Better Shoving

Content.Shared/CCVar/CCVars.Chat.cs
Описание.
---
:cl: vanx
- tweak: Лимит длины оповещений увеличен до 1000 символов.
=> [Tweak] Announcement Character Limit

Content.Client/Crayon/CrayonSystem.cs, Content.Client/_White/Overlays/CrayonPreviewOverlay.cs, Content.Server/Crayon/CrayonSystem.cs
:cl:
- fix: Мелкофикс оверлея для мелков.
=> weed eater

Content.Client/FootPrint/FootPrintsVisualizerSystem.cs, Content.IntegrationTests/Tests/Fluids/AbsorbentTest.cs, Content.Server/Fluids/EntitySystems/AbsorbentSystem.Footprints.cs, Content.Server/Fluids/EntitySystems/AbsorbentSystem.cs, Content.Server/FootPrint/FootPrintsSystem.cs, Content.Shared/Footprint/FootPrintComponent.cs, Content.Shared/Footprint/FootPrintsComponent.cs
:cl:
- fix: Чисто бот теперь работает
- fix: Меньше лагов из-за следов
=> [Fix] Footstep

Content.Client/Weapons/Ranged/GunSpreadOverlay.cs, Content.Client/Weapons/Ranged/Systems/GunSystem.cs, Content.Server/NPC/Systems/NPCCombatSystem.Ranged.cs, Content.Server/Projectiles/ProjectileSystem.cs, Content.Shared/CCVar/CCVars.GhostRespawn.cs, Content.Shared/MagicMirror/SharedMagicMirrorSystem.cs, Content.Shared/Projectiles/ProjectileComponent.cs, Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs, Content.Shared/Wieldable/WieldableSystem.cs, Resources/ConfigPresets/Build/development.toml, Resources/Locale/ru-RU/weapons/grenades/timer-trigger.ftl, Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Projectiles/toy_projectiles.yml, Resources/Prototypes/Entities/Objects/Specific/Salvage/ore_bag.yml, Resources/Prototypes/Entities/Objects/Weapons/Bombs/plastic.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/fireaxe.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/stunprod.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/sword.yml, Resources/Prototypes/Entities/Objects/Weapons/Throwable/bola.yml, Resources/Prototypes/Entities/Objects/Weapons/Throwable/clusterbang.yml, Resources/Prototypes/Entities/Objects/Weapons/security.yml, Resources/Prototypes/_White/Entities/Objects/Weapons/Guns/launchers.yml, Resources/Prototypes/_White/themes.yml, Resources/Prototypes/themes.yml
- Фикс тестов из-за увеличенного размера протокинетика.
- Мечи и мачете могут резать при готовке и крафтах.
- Поворот анимации станбатона.
- NPC теперь попадают по лежачим.
- Лишняя строка описания у оружия.
- Пульки теперь имеют гравитацию.
- Спец. гранатомёт пофикшен и может стрелять энергоболами, кластерными флешками и взрыв. зарядами.
- Убраны линии минимального разброса при стрельбе.
- Линии разброса при стрельбе теперь имеют цвет выбранной темы интерфейса.
- Выключен лаваленд в дебаге.
- Убран максимальный лимит игроков при попытке вернуться в раунд.
- Починены зеркала.
---
:cl: vanx
- fix: Мобы и турели теперь попадают по лежачим персонажам.
- fix: Зеркала теперь работают на стене.
- tweak: Теперь можно вернуться в раунд независимо от количества игроков.
=> [Fix] General Fixes

Content.Client/Weapons/Melee/MeleeWeaponSystem.cs, Content.Server/Weapons/Melee/MeleeWeaponSystem.cs, Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs
Исправлены анимации толкация, теперь должны отображаться корректно.
Т.к. есть анимации, убрал спам попапами.
Толкание предметов теперь тратит столько же стамины как и бросок.
Проверил работу с CQC - вроде всё ок.
---
=> [Tweak] Shove 3

Resources/Prototypes/Entities/Objects/Decoration/flora.yml
ломание новогодней ёлки больше не вешает на игрока смайт с табличкой KILL
выглядит уебански, рп игра все дела
=> [Remove] Non-admin KILL Signs

Content.Shared/Movement/Pulling/Systems/PullingSystem.cs, Resources/Prototypes/Catalog/Fills/Lockers/security.yml
cl
-->
:cl: vanx
- fix: Исправлены кулдауны броска грабом (4 секунды).
- remove: Пояса дзюдо из шкафов СБ.
=> [Fix] CQC 

Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/caseless_rifle.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/heavy_rifle.yml, Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/Loadouts/Jobs/Security/headOfSecurity.yml, Resources/Prototypes/Loadouts/Jobs/Security/uncategorized.yml, Resources/Prototypes/Research/arsenal.yml
СБ теперь не может взять раундстартом/изучить/напечатать оружие синдиката.
Удалены пушки "для нагиба" и энергомеч в лодаутах ХОСа.
Убрано чрезмерное количество опций вооружения в лодаутах СБ.
Пофикшен принтер денег безгильзовыми патронами.
Безгильзовые патроны и автомат на них перенесены в Т3 изучение арсенала.
Станция не может бесконечно печатать бронежилеты и СБхуды.
---
<p>
</p>
</details>
---
:cl: vanx
- remove: Оружие синдиката у СБ и в изучениях РНД.
- fix: Печать денег с помощью безгильзовых патронов.
=> [Tweak] Security/Station Guns

Content.Shared/Projectiles/SharedProjectileSystem.cs, Resources/Locale/ru-RU/armor/armor-examine.ftl, Resources/Locale/ru-RU/weapons/throwing/throwing.ftl
=> [Fix] Embed Locale

Content.Shared/Storage/Components/SharedEntityStorageComponent.cs
Описание.
cl
:cl: vanx
- fix: Открытые шкафы теперь не ловят пули и лазеры.
=> [Fix] Lockers Catching Bullets

Content.Server/Weapons/Melee/MeleeWeaponSystem.cs, Content.Shared/Throwing/ThrowingSystem.cs, Content.Shared/_White/CVars.cs
Толкание теперь запускает в воздух только предметы.
small fix no CL
=> [Tweak] Shove 4

Resources/Migrations/WWDPMigration.yml, Resources/Prototypes/Catalog/Fills/Lockers/heads.yml, Resources/Prototypes/Catalog/Fills/Lockers/security.yml, Resources/Prototypes/Catalog/Fills/Lockers/suit_storage.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/magnum.yml
:cl: vanx
- remove: РПГ-7 и лазерные дробовики с карт, дисейблеры из шкафов СБ, шкафы синего щита и представителя НТ, двойные скафандры СБ.
=> [Tweak] Less Roundstart Guns

Resources/Prototypes/Catalog/Cargo/cargo_armory.yml, Resources/Prototypes/Catalog/Cargo/cargo_medical.yml, Resources/Prototypes/DeltaV/Catalog/Cargo/cargo_armory.yml
Описание.
Убрана пушка для нагиба и полурабочий дробовик с дельты в в карго, майндщилды перенесены в арсенал.
---
no cl
=> [Tweaks] Cargo

Resources/Prototypes/GameRules/roundstart.yml
Описание.
Так как лояльность всех революционеров зависит от того что главы революции живы, логично поднять минимальное количество глав (1 -> 2). Таким образом революция будет иметь меньше шансов закончиться в рандомный момент из за смерти единственного главы, а сами главы смогут кооперировать действия между собой.
Заодно поднято максимальное количество глав при онлайне >60 игроков (2 -> 3). 
---
:cl: vanx
- tweak: Режим революции теперь начинается минимум с двумя главами революции.
=> [Tweak] Glorious Revolution

Resources/Migrations/eeMigration.yml, Resources/Prototypes/CharacterItemGroups/Jobs/Command/captain.yml, Resources/Prototypes/CharacterItemGroups/Jobs/Security/headOfSecurity.yml, Resources/Prototypes/Loadouts/Jobs/Command/captain.yml, Resources/Prototypes/Loadouts/Jobs/Security/headOfSecurity.yml
Описание.
Из лодаутов убраны импульсные пистолеты ЕРТ. 
Лазер капитана убран из лодаутов и возвращён в сейф на станции.
---
:cl: vanx
- tweak: Лазер капитана снова появляется в стеклянном сейфе на станции.
=> [Remove] Laser Loadouts

Content.Client/Lobby/UI/LobbyGui.xaml.cs, Resources/Prototypes/DeltaV/Roles/Jobs/Command/administrative_assistant.yml, Resources/Prototypes/DeltaV/Roles/Jobs/Justice/chief_justice.yml, Resources/Prototypes/DeltaV/Roles/Jobs/Justice/clerk.yml, Resources/Prototypes/DeltaV/Roles/Jobs/Justice/prosecutor.yml, Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/gladiator.yml, Resources/Prototypes/Nyanotrasen/Roles/Jobs/Wildcards/martialartist.yml, Resources/Prototypes/Roles/Jobs/Wildcards/boxer.yml, Resources/Prototypes/Roles/Jobs/Wildcards/zookeeper.yml, Resources/Prototypes/Roles/Jobs/departments.yml, Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml, Resources/Prototypes/_Goobstation/Roles/Jobs/Command/magistrate.yml, Resources/Prototypes/_Goobstation/Roles/Jobs/Command/nanotrasen_representative.yml
Из меню выбора ролей убраны неиспользуемые.
Убраны неиспользуемые и дублирующие категории ролей.
Название фона лобби, трека, и голосования теперь не перекрывают меню редактирования персонажа.
:cl: vanx
- remove: Из меню выбора ролей убраны неиспользуемые.
- fix: Название фона лобби, трека, и голосования теперь не перекрывают меню редактирования персонажа.
=> [Tweak] Character Creation Cleanup

Content.Server/Antag/AntagSelectionSystem.cs, Content.Shared.Database/LogType.cs
Описание.
Добавляет отдельные логи становления антагом и вкладку для них.
no cl
=> [Add] Antag Logging

Resources/Prototypes/_White/Roles/Jobs/Command/maid.yml
Убраны лишние доступы у мейдочки.
---
no cl
=> [Tweak] Maid Access

Resources/Maps/_Lavaland/Lavaland/outpost_lavaland.yml
Временно убран сервер и консоль датчиков экипажа с лаваленда, т.к. он мешал работе датчиков станции.
---
:cl: vanx
- fix: Мониторинг датчиков экипажа станции снова работает
=> [Fix] Station Crew Monitors

Resources/Prototypes/Entities/Structures/Furniture/toilet.yml
Описание.
---
---
:cl: vanx
- fix: Коллизии унитазов и возможность интерактировать с ними.
=> [Fix] Skibidi Toilets Can No Longer Go Through Walls And Be Untouchable

Resources/Prototypes/DeltaV/Entities/Clothing/Eyes/glasses.yml, Resources/Prototypes/DeltaV/Recipes/Construction/Graphs/clothing/glasses_corpshud.yml, Resources/Prototypes/DeltaV/Recipes/Construction/clothing.yml, Resources/Prototypes/Entities/Clothing/Eyes/hud.yml, Resources/Prototypes/_Goobstation/Entities/Clothing/Eyes/glasses.yml
:cl: vanx
- fix: Очки бригмедика теперь показывают здоровье.
- fix: Крафт очков бригмедика заменён на (работающий) крафт очков медсек.
=> [Fix] Corpsman Hud Glasses

Resources/Prototypes/Entities/Objects/Weapons/Guns/LMGs/lmgs.yml
Убирает увеличение разброса, которое делало L6 неуправляемым при стрельбе и лишало его его основной роли - стационарного подавления на средней дистанции.
По итогу мы получаем стабильную платформу для стационарного и защитного боя, т.к. разброс при движении всё ещё огромный.
---
https://github.com/user-attachments/assets/6ae0b864-62e9-4252-b183-03e25642fe0a
---
:cl: vanx
- tweak: Пулемёт L6 SAW теперь не теряет точность при стрельбе без движения.
=> [Tweak] L6 SAW Spread

Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
Тесты должны работать 
---
no cl
=> [Fix] Test

Content.Shared/_Goobstation/MartialArts/Components/GrabStagesOverrideComponent.cs
cl
---
:cl: vanx
- remove: Моментальный хард граб у владельцев рукопашного боя.
=> [Tweak] No Instant Hard Grab

Resources/Prototypes/Entities/Clothing/Back/satchel.yml, Resources/Prototypes/Entities/Objects/Consumable/Smokeables/base_smokeables.yml, Resources/Prototypes/Entities/Objects/Tools/flashlights.yml, Resources/Prototypes/Entities/Objects/Tools/gas_tanks.yml
:cl: vanx
- fix: Надетые сумки теперь открываются.
- fix: Также можно интерактировать с надетыми сигаретами, фонариками и баллонами.
=> [Fix] Immersion Sim 2

Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/pka.yml
:cl: vanx
- fix: Шахтёрский ускоритель частиц больше не помещается в карман.
=> [Fix] Pocket Accelerator

Resources/Prototypes/Loadouts/Jobs/Security/uncategorized.yml, Resources/Prototypes/_DEN/Loadouts/Jobs/Security/uncategorized.yml
:cl: vanx
- fix: Заключённый больше не может брать общее снаряжение и личное оружие СБ в лодаутах.
=> [Remove] Blicky

Resources/Maps/Shuttles/pirateradio.yml
:cl: vanx
- remove: Бесплатные ящики со снаряжением синдиката со станции прослушки.
=> [Remove] Listening Post Loot

Resources/Prototypes/Traits/physical.yml
Трейт на спинаретку теперь позволяет крафтить из паутины всякое
:cl:
- add: Трейт на спинаретку полезное
=> Spinoretka

Resources/Prototypes/Entities/Objects/Materials/materials.yml, Resources/Prototypes/Entities/Objects/Specific/revolutionary.yml, Resources/Prototypes/_White/Entities/Objects/Misc/paper.yml, Resources/Prototypes/_White/Recipes/Crafting/alternate.yml, Resources/Prototypes/_White/Recipes/Crafting/fun.yml, Resources/Prototypes/_White/Recipes/Reactions/Synthesis.yml, Resources/Prototypes/_White/tags.yml
Новые рецепты крафта и реакции
Рецепты крафта бумаги и картона, а также коммунистической пропаганды. Вива ля революшн!
---
<p>
</p>
</details>
---
:cl: Ligrof
- add: реакция создания бумаги и коммунистической бумаги
- add: рецепт крафта картона и революционного манифеста
=> Синтез бумаги и клейка картона, а также написание революционной книжки

Resources/Prototypes/Recipes/Reactions/biological.yml
Маленький фикс раздражающей детали
---
:cl:
- tweak: Количество воды на выходе из центрифугирования крови 11 => 10.5
=> Фикс маленькой детали

Content.Client/Entry/EntryPoint.cs, Content.Client/Options/UI/Tabs/GraphicsTab.xaml, Content.Client/Options/UI/Tabs/GraphicsTab.xaml.cs, Content.Client/Parallax/ParallaxControl.cs, Content.Client/_White/Overlays/GrainOverlay.cs, Content.Shared/CCVar/CCVars.cs, Content.Shared/_White/CVars.cs, Resources/Locale/en-US/_white/escape-menu/options-menu.ftl, Resources/Locale/ru-RU/_white/escape-menu/options-menu.ftl, Resources/Prototypes/_White/Shaders/shaders.yml, Resources/Textures/_White/Shaders/grain.swsl
Порт шума с старовд.
---
<p>
</p>
</details>
---
- add: Шум со старовд
=> [PORT] Кинематографичная рябь, или по простому шум

Resources/Prototypes/_Goobstation/Changeling/Entities/Objects/Weapons/Melee/changeling_armblade.yml
Уээ, смотри чейнжлоги. Make armblade great again!
---
:cl:
- tweak: Урон руки-клинка 15 -> 25
=> [TWEAK] Бафф армблейда

Resources/Prototypes/Entities/Structures/Machines/chem_master.yml, Resources/Prototypes/_White/Recipes/Reactions/Synthesis.yml, Resources/Prototypes/_White/Recipes/Reactions/biological.yml
Немного реакций разложения и синтез биомассы
---
:cl:
- add: Рецепт биомассы, разложения сахара и разложения универсального фермента
- tweak: макс емкость таблеток 20 -> 50
=> Some chemical reactions

Content.Client/UserInterface/Screens/SeparatedChatGameScreen.xaml, Content.Client/UserInterface/Systems/Alerts/Widgets/AlertsUI.xaml
This reverts commit febd9a565fc72499697860b247b0908d9c3f0bc2.
я обосрался ревертните
---
<p>
</p>
</details>
---
- remove: юи в порядке
=> Revert "[Tweak] Перенос юи уведомлений или что это (#353)"

Content.Server/_White/Hearing/HearingSystem.cs
Исправлен баг при котором с персонажей не снималась глухота
=> [Fix] Fix Deafnesss

Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Bow/hardlight_bow.yml, Resources/Prototypes/_White/Entities/Objects/Weapons/Guns/Battery/mini_ebow.yml
Мини арбалет на то и мини, что должен давать такой же угол что и пистолет. Энерго-лук легче обычного лука (свет ничего не весит), его теперь немного удобнее использовать.
---
<p>
</p>
</details>
---
:cl:
- tweak: Из мини энерго-арбалет теперь удобнее стрелять на бегу
- tweak: Из энерго-лука теперь немного удобнее стрелять на бегу
=> [Tweak] Balance

Content.Server/_Goobstation/Changeling/ChangelingSystem.Abilities.cs, Resources/Prototypes/_Goobstation/Changeling/Entities/Mobs/headcrab.yml
=> [Fix] Changeling Headcrad Id

Resources/Prototypes/Traits/physical.yml
:cl:
- fix: Некоторые трейты снова отключены
=> [Fix] Traits

Content.Server/Atmos/EntitySystems/FlammableSystem.cs
Описание
---
:cl:
- fix: Огонь снова работает нормально
=> [Fix] Fire

Content.Server/_Goobstation/Changeling/ChangelingSystem.cs, Content.Shared/_Goobstation/Changeling/ChangelingComponent.cs
Удалено пассивное уменьшение биомассы у генокрада, а также её отображение за ненадобностью. Сверхсильный мутант, умирающий от недоедания за 15 минут - не круто.
---
:cl:
- remove: Отключена биомасса у генокрада. (Фактически она все еще есть в коде, а её значение может редактироваться педалями через VV)
=> [REMOVE] Отключена биомасса

Resources/Locale/en-US/_Goobstation/bingle/bingle.ftl, Resources/Prototypes/_Goobstation/GameRules/bingleEvent.yml
Раскоментирован и изменён ивент бинглов. Теперь они должны спавнится в раунде без педального вмешательства.
---
:cl:
- tweak: Яма будет расти! Бинглы теперь могут появиться в раунде без педального вмешательства.
=> [Tweak] Яма. Должна. Расти

Content.Client/Paper/UI/PaperWindow.xaml.cs, Content.Client/UserInterface/RichText/MonoTag.cs
Добавлен моно шрифт для текстовых бумаг.
Оригинальный ПР https://github.com/space-wizards/space-station-14/pull/33830
=> [Port] Monospace Support for Rich Text

Content.Shared/Damage/Systems/RequireProjectileTargetSystem.cs
:cl: vanx
- tweak: Лежачие персонажи больше не уклоняются от пуль при движении
=> [Tweak] Crawling

Resources/Textures/_White/Shaders/flickerhologram.swsl
:cl:
- fix: Режим совместимости теперь работает. Если у вас есть какие-то проблемы с белизной экрана при использовании режима совместимости, то отключите зернистость в настройках графики.
=> [Fix] Compatibility Mode

Content.Server/Atmos/EntitySystems/FlammableSystem.cs, Content.Server/EntityEffects/Effects/ExtinguishReaction.cs, Content.Server/EntityEffects/Effects/FlammableReaction.cs
:cl:
- fix: Жидкости больше не поджигают цель напрямую
=> [Fix] Flammable

Content.IntegrationTests/PoolManagerTestEventHandler.cs, Resources/Prototypes/Maps/anchor.yml, Resources/Prototypes/_White/Entities/Objects/Specific/Medical/hypospray.yml
=> [Fix] Yaml linter

Content.Server/Traits/TraitSystem.cs, Content.Shared.Database/LogType.cs
Когда игроку выдается трейт, система создает запись в логах.
Эти логи можно просматривать через админ-панель, где они будут отображаться в отдельной категории "Trait"
---
<p>
</p>
</details>
---
:cl: Kutos
- add: Добавлено логгирование трейтов.
=> [ADD] "Логгирование трейтов"

Content.Server/Speech/EntitySystems/LizardAccentSystem.cs
Добавляет перевод ящерского акцента.
---
:cl: Kutossssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
- add: Добавлен русский акцент ящеров.
=> [ADD] "Русссский акссент ящщуров"

Content.Server/_Goobstation/Chemistry/TakeStaminaDamage.cs, Resources/Locale/en-US/_Goobstation/reagents/meta/narcotics.ftl, Resources/Locale/ru-RU/_Goobstation/reagents/meta/narcotics.ftl, Resources/Prototypes/_Goobstation/Reagents/narcotics.yml, Resources/Prototypes/_Goobstation/Reagents/toxins.yml
Этот PR добавляет непортированые, но нужные для работы жал, химикаты с губа
:cl:
- fix: Все жала генокрада теперь должны работать.
- add: Ослепляющий токсин (доступен только для жал генокрада и педалей).
- add: Тиризен - вызывает урон по стамине (доступен только для жал генокрада и педалей).
=> [Fix] Жала генокрада

Resources/Prototypes/Nyanotrasen/Entities/Mobs/Species/felinid.yml
Фелинидам выданы эмоуты фелинидов
:cl:
- fix: Фелиниды снова умеют мяукать
=> [Fix] Meow!

Content.Server/_Goobstation/Bingle/BinglePitSystem.cs
Почему так не было до этого? Это просто не правильно воровать стопку стали, или полный шкафчик, а получать всего одно очко!
:cl:
- tweak: Теперь если в яму бинглов закинуть любой контейнер - очки будут прибавляться за каждую сущность, содержащуюся в этом контейнере. 
- tweak: Теперь если в яме бинглов окажется стак чего-либо, то количество прибавленных очков будет равно количеству предметов в стаке.
=> [Tweak] THE PIT MUST GROW

Content.Server/_White/Commands/PoshelnahuiCommand.cs
=> Poshelnahui

Content.Shared/_Goobstation/MartialArts/SharedMartialArtsSystem.CQC.cs
cl
---
---
:cl:
- tweak: Перенесено разоружение из Pressure в Restrain
=> [Tweak] CQC disarm

Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
:cl:
- fix: Исправлены отсутствующие вайтлисты на оружия
=> [Fix] Whitelist

Content.Shared/Movement/Pulling/Components/PullerComponent.cs, Content.Shared/Movement/Pulling/Systems/PullingSystem.cs
:cl:
- tweak: Шанс выбраться при софт грабе теперь равен 100%
- fix: Застаненый человек больше не может сопротивляться при грабе
=> [Fix] Grab

Content.Server/StoreDiscount/Systems/StoreDiscountSystem.cs, Content.Shared/StoreDiscount/Components/StoreDiscountComponent.cs, Resources/Prototypes/Entities/Objects/Specific/syndicate.yml
:cl:
- fix: У ядерных оперативниках снова появились скидки в аплинке
=> [Fix] Uplink Discount

Resources/Prototypes/_White/GameRules/midround.yml
Ивент только для педального насера, что бы не воровать людей со станции
---
no cl
=> [Add] Mid Round Nuke Ops

Content.Server/_White/Administration/Commands/InvisibilityCommand.cs, Content.Server/_White/Administration/Commands/VisibilityCommand.cs, Content.Shared/Eye/VisibilityFlags.cs, Resources/Locale/en-US/_white/administration/commands/invisibility.ftl, Resources/Locale/ru-RU/_white/administration/commands/invisibility.ftl, Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml
Команда для педалек что бы делать свой гост невидимым для остальных (кроме других педалей)
---
no cl
=> [Add] Invisibility

Resources/Prototypes/Psionics/PsionicPowerPool.yml, Resources/Prototypes/Psionics/psionics.yml
рендом пул псионических способностей теперь изначально имеет в себе все возможные умения, раньше нужно было получить определённую способность, за которой шла другая, но шанс на получение действительно опасной способности крайне мал.
если псионика наконец-то начнёт представлять хоть какую-то опасность, за ней начнут действительно следить, и это будет делать не одинокий мантист, а целый отряд СБ с таблеточками
:cl:
- tweak: Псионики стали опаснее
=> psionica is fun dont nerf psionica pz

Content.Shared/Traits/Assorted/Systems/PermanentBlindnessSystem.cs
Слепоту от трейта теперь нельзя вылечить пересадкой. 
---
No CL, сюрпризом будет)
=> [Tweak] Минус глазки 

Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
Теперь скафандр бригмедика будет замедлять передвижение на 25% вместо 35%.
---
:cl: Kutos
- tweak: Замедление скафандра бригмедика 35% -> 25%
=> [Tweak] Скафандр бригмедика

Resources/Prototypes/Recipes/Lathes/robotics.yml
Голова сервисного борга теперь имеет рецепт. 
---
:cl: Kutos
- fix: Рецепт для головы сервисного борга
=> [MINI-FIX] Цена за голову борга

Resources/Prototypes/Entities/Objects/Specific/chemistry.yml, Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/syringe_gun.yml
Небольшое усиление шприцеметов. 
---
:cl: Kutos
- tweak: Усиление шприцеметов
=> [Tweak] бафф шприцемета

Resources/Prototypes/Traits/physical.yml
:cl:
- remove: Убран Restricted Gear трейт
=> [Fix] Disable RestrictedGear

Resources/Prototypes/Entities/Objects/Specific/Medical/morgue.yml
:cl:
- fix: Мешки для тел больше нельзя просунуть под дверьми
=> [Fix] Body Bag Fixtures

Content.Shared/Mobs/Systems/MobStateSystem.Subscribers.cs, Content.Shared/Mobs/Systems/MobStateSystem.cs, Content.Shared/Standing/SharedLayingDownSystem.cs, Content.Shared/Stunnable/SharedStunSystem.cs, Content.Shared/_White/Collision/LayDown/LayDownOnCollideSystem.cs
:cl:
- fix: Трупы теперь не могут таскать вещи
=> [Fix] Lay Down

Content.Server/Guardian/GuardianSystem.cs
:cl:
- fix: Из голоклоуна больше не выпадают органы при смерти хозяина
=> [Fix] Holoclown

Content.Client/Research/UI/ResearchConsoleMenu.xaml.cs, Content.Client/Research/UI/TechnologyCardControl.xaml.cs, Content.Server/Research/Systems/ResearchSystem.Console.cs, Content.Server/Research/Systems/ResearchSystem.Technology.cs, Content.Shared/Research/Components/ResearchServerComponent.cs, Content.Shared/Research/Components/TechnologyDatabaseComponent.cs, Content.Shared/Research/Systems/SharedResearchSystem.cs
:cl:
- fix: Множитель очков исследования теперь един для всех консолей
=> [Fix] Research Point Multiplier

Content.Shared/Clothing/EntitySystems/SkatesSystem.cs
:cl:
- fix: Роликовые коньки больше на заставляют вас скользить если их снять
=> [Fix] Roller Skates

Content.Client/Atmos/UI/GasAnalyzerWindow.xaml.cs
---
N/A
---
:cl:
- fix: Теперь окно газоанализатора сразу открывается с правильной шириной.
=> [FIX] микрофикс газана

Resources/Prototypes/Loadouts/Generic/hands.yml, Resources/Prototypes/Loadouts/Jobs/Security/uncategorized.yml
:cl:
- tweak: Боевые перчатки теперь не доступны всем членам службы безопасности
- remove: Удалены боевые перчатки ТСФА из лодаутов
- remove: Удалена броня ТСФА из лодаутов службы безопасности
=> [Fix] Loadout

Content.Server/Radio/EntitySystems/HeadsetSystem.cs, Content.Server/Radio/EntitySystems/RadioSystem.cs, Content.Server/_White/TTS/TTSSystem.Sanitize.cs, Resources/Locale/ru-RU/headset/headset-component.ftl
Исправлено отображение в радиоканалах, и, ВОЗМОЖНО, в ттс.
--
No cl
=> [FIX] Шрифт клоуна

Resources/Locale/ru-RU/store/uplink-catalog.ftl, Resources/Prototypes/Catalog/uplink_catalog.yml
cl
---
:cl:
- fix: В аплинк возвращены старые воровские перчатки
=> [FIX] Thieving Gloves

Resources/Prototypes/Language/Species-Specific/Xeeplian.yml
Описание.
:cl:
- tweak: Изменён шрифт абдукторов на BoxFont Round. Он должен корректно отображаться в чате.
=> [Tweak] Шрифт абдукторов

Content.Shared/Containers/ContainerFillSystem.cs, Content.Shared/Weapons/Melee/MeleeWeaponComponent.cs
По идеи теперь проходит тесты. Анимация ударов снова работает
=> [Fix] Upstream

Resources/Prototypes/Reagents/medicine.yml, Resources/Prototypes/Recipes/Reactions/medicine.yml, Resources/Prototypes/_White/Reagents/gases.yml
попытка номер 2, слегка все переделал теперь нормально
:cl: Boevi4ok
- tweak: сильно изменены характеристики препаратов для криогеники
=> [TWEAK] Make krio grate again 

Content.Server/Hands/Systems/HandsSystem.cs, Content.Server/_White/Throwing/ReturnItemOnThrowSystem.cs, Content.Server/_White/Throwing/ThrowingItemModifierSystem.cs, Content.Shared/CCVar/CCVars.Atmos.cs, Content.Shared/Damage/Systems/SharedDamageOtherOnHitSystem.cs, Resources/Prototypes/WhiteDream/Entities/Objects/Weapons/Melee/cult.yml, Resources/Prototypes/_White/Entities/Clothing/Belt/modsuits.yml
Модификатор силы броска теперь менее щиткодный
----------
:cl:
- tweak: Космический ветер должен стать лучше
- tweak: Вещи снова отскакивают при попадании
- fix: Модсьют инфилтрятор теперь можно активировать
- fix: Втыкаемые снаряды вновь наносят урон при попадании
=> [Fix] Bugs

Content.Server/Procedural/DungeonSystem.Rooms.cs, Content.Server/Procedural/DungeonSystem.cs
Исправление несохранившихся кастомных объектов в структурах
=> [Fix] Dugeon

Content.Server/Procedural/RoomFillSystem.cs, Resources/Prototypes/_White/Entities/Markers/rooms.yml
Точка спавна комнаты теперь является нулевыми кординатами
---
no cl
=> [Tweak] Dungeon Spawn

Content.Shared/_White/Guns/SharedGunOverheatSystem.cs
Reverts WWhiteDreamProject/wwdpublic#520
Не работает.
=> Revert "[Fix] Regulator Lamp Visuals"

Content.Shared/Projectiles/EmbedPassiveDamageSystem.cs
:cl:
- fix: Световое копье больше не наносит урона после удаления
=> [Fix] Embed Passive Damage

Resources/Prototypes/GameRules/roundstart.yml
Ручки все таки дотянулись
:cl: Boevi4ok
- remove:  недо антаг УБИТ
=> [TWEAK] Actually great for game

Resources/Prototypes/_Goobstation/Entities/Objects/Specific/Fishing/loot_tables.yml
Бафф шансов выпадения рыбы при рыбалке. Уменьшение шанса выпадения мусора и другого.
---
</p>
</details>
---
:cl: Aposto2 (Frogman)
- tweak: Изменение шансов выпадения лута в рыбалке. Теперь мусор - 35%, обычная рыба - 45%, редкая рыба - 15%, легендарная рыба - 5%
=> [TWEAK] Fish chances buff in fishing

Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
Вернул проёбаное изменение из #325
:cl: vanx
- fix: Силовик снова стреляет в полуавтоматическом режиме
=> [Fix] Enforcer is semi auto again

Resources/Prototypes/_White/Entities/Structures/Other/traps.yml
=> [Fix] Booby Trap Collision

Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/Recipes/Lathes/misc.yml, Resources/Prototypes/_White/Recipes/Lathes/misc.yml
:cl: vanx
- add: Крафт коробка спичек в автолате
=> [Add] Matchbox Autolathe Recipe

Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.Interactions.cs, Resources/Locale/ru-RU/weapons/ranged/gun.ftl
=> [Fix] Damage Modifiers on Examine + Locale

Resources/Prototypes/Traits/physical.yml
трейты красная рубашка и упорство теперь взаимоисключающие
=> [Fix] Infinite Crit

Resources/Prototypes/Loadouts/Jobs/Command/captain.yml, Resources/Prototypes/Loadouts/Jobs/Command/headOfPersonnel.yml, Resources/Prototypes/Loadouts/Jobs/Engineering/chiefEngineer.yml, Resources/Prototypes/Loadouts/Jobs/Epistemics/mystagogue.yml, Resources/Prototypes/Loadouts/Jobs/Logistics/logisticsOfficer.yml, Resources/Prototypes/Loadouts/Jobs/Medical/chiefMedicalOfficer.yml, Resources/Prototypes/Loadouts/Jobs/Security/headOfSecurity.yml
Убрал понтовые ПДА из лодаутов, которые некорректно спавнились с безымянной картой
=> [Remove] Shitty PDA Loadouts

Content.Server/Silicons/Laws/SiliconLawSystem.cs, Content.Shared/Silicons/Laws/Components/EmagSiliconLawComponent.cs, Resources/Prototypes/Entities/Mobs/Player/silicon.yml, Resources/Prototypes/Entities/Objects/Specific/Robotics/mmi.yml, Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Теперь если тыкнуть ЕМАГом по консоли аплоуда - можно будет подчинить ИИ станции себе.
---
:cl:
- add: Добавлен взлом аплоуда ЕМАГом, что заставляет ИИ подчиняться вам. Взломанные законы невозможно сменить. Have fun!
=> [Feature] Ai subvert

Content.Shared/CCVar/CCVars.LayingDown.cs
:cl: vanx
- remove: Отключена возможность прятаться под столами
=> [Disable] Crawling Under Tables

Resources/Prototypes/Damage/modifier_sets.yml, Resources/Prototypes/Entities/Objects/Devices/station_beacon.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/turrets/turrets_base.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/turrets/turrets_broken.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/baseball_bat.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/fireaxe.yml, Resources/Prototypes/Entities/Structures/Doors/MaterialDoors/material_doors.yml, Resources/Prototypes/Entities/Structures/Doors/Shutter/blast_door.yml, Resources/Prototypes/Entities/Structures/Doors/Windoors/base_structurewindoors.yml, Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml, Resources/Prototypes/Entities/Structures/Machines/base_structuremachines.yml, Resources/Prototypes/Entities/Structures/Machines/cloning_machine.yml, Resources/Prototypes/Entities/Structures/Machines/fatextractor.yml, Resources/Prototypes/Entities/Structures/Machines/medical_scanner.yml, Resources/Prototypes/Entities/Structures/Power/Generation/Singularity/emitter.yml, Resources/Prototypes/Entities/Structures/Power/apc.yml, Resources/Prototypes/Entities/Structures/Power/smes.yml, Resources/Prototypes/Entities/Structures/Power/substation.yml, Resources/Prototypes/Entities/Structures/Storage/Crates/base_structurecrates.yml, Resources/Prototypes/Entities/Structures/Walls/girders.yml, Resources/Prototypes/Entities/Structures/Walls/walls.yml, Resources/Prototypes/Entities/Structures/catwalk.yml, Resources/Prototypes/Entities/Structures/meat_spike.yml, Resources/Prototypes/Entities/Structures/soil.yml, Resources/Prototypes/Entities/Structures/stairs.yml, Resources/Prototypes/Nyanotrasen/Entities/Structures/Storage/Closets/Lockers/lockers.yml, Resources/Prototypes/_Nuclear14/Entities/Structures/Walls/slantedwalls.yml, Resources/Prototypes/_Nuclear14/Entities/Structures/Walls/tallwalls.yml
:cl: vanx
- tweak: Структурный урон снова эффективен по структурам
=> [Tweak] Structural Damage

Resources/Prototypes/Entities/Structures/Doors/SecretDoor/secret_door.yml, Resources/Prototypes/Entities/Structures/Walls/girders.yml, Resources/Prototypes/Recipes/Construction/Graphs/structures/girder.yml, Resources/Prototypes/Recipes/Construction/Graphs/structures/secretdoor.yml, Resources/Prototypes/Recipes/Construction/structures.yml
Рецепт создания секретных дверей был изменён на тот, что используется на ТэГэ стэйшоне. Почему? Из-за их ужасающего крафта на данный момент ими почти никто не пользуется (Он требовал батарейки и провода, камон, как это относится к секретной двери). Теперь для ее создания требуется сделать каркас, открутить его от пола и нажать по нему двумя листами стали.
---
:cl:
- tweak: Изменён крафт потайной двери. Теперь требуется создать каркас, открутить его от пола и нажать по нему двумя листами стали.
=> [Tweak] Рецепт создания секретных дверей

Content.Server/Weapons/Melee/MeleeWeaponSystem.cs
=> [Fix] Melee Damage Examine

Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
:cl: vanx
- tweak: Масса королевы ксеноморфов: 9861 -> 477.
- fix: Бросок королевой ксеноморфов больше не гибает и не уничтожает стены при попадании.
=> [Fix] Xeno Queen Gibbing On Hit When Thrown

Resources/Prototypes/Entities/Clothing/Belt/belts.yml, Resources/Prototypes/_EE/Entities/Clothing/BieselRepublic/belts.yml
:cl: vanx
- tweak: Тактические разгрузки теперь звучат тише при ходьбе
- remove: Убран звук при ходьбе у кобуры и разгрузки утилизаторов.
=> [Tweak] Belt Gear Sounds

Resources/Prototypes/Damage/modifier_sets.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml, Resources/Prototypes/Entities/Structures/Windows/window.yml
фикс урона протокинетиком по камням и структурного по окнам
=> [Fix] Structure Damage 

Content.Client/_White/DollyMixture/DollyMixtureSystem.cs
=> [fix] extremely loud incorrect buzzer

Resources/Prototypes/Catalog/VendingMachines/Inventories/chapel.yml, Resources/Prototypes/DeltaV/Entities/Clothing/Head/hats.yml, Resources/Prototypes/DeltaV/Entities/Clothing/OuterClothing/vests.yml, Resources/Prototypes/Entities/Clothing/Head/hats.yml, Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml, Resources/Prototypes/Entities/Clothing/OuterClothing/coats.yml, Resources/Prototypes/Entities/Clothing/OuterClothing/misc.yml, Resources/Prototypes/Entities/Clothing/OuterClothing/suits.yml, Resources/Prototypes/Entities/Clothing/OuterClothing/vests.yml, Resources/Prototypes/Nyanotrasen/Entities/Clothing/OuterClothing/misc.yml, Resources/Prototypes/Nyanotrasen/Entities/Clothing/OuterClothing/robes.yml, Resources/Prototypes/Nyanotrasen/Entities/Clothing/OuterClothing/vests.yml, Resources/Prototypes/_EE/Entities/Clothing/OuterClothing/jackets.yml, Resources/Prototypes/_White/Entities/Clothing/OuterClothing/coats.yml
:cl: vanx
- add: Больше вещей одежды получили возможность разделки на ткань и/или инвентарь.
=> [Add] More Butcherable Clothes

Resources/Prototypes/Catalog/Fills/Lockers/heads.yml, Resources/Prototypes/Catalog/Fills/Lockers/security.yml, Resources/Prototypes/_White/Loadouts/Jobs/security.yml
плюс убрал ещё лишние лодауты, что уже есть в отделе
:cl: vanx
- tweak: Противогазы СБ перемещены в шкафы в отделе.
=> [Tweak] Security Masks In Lockers

Resources/Prototypes/Entities/Objects/Specific/revolutionary.yml, Resources/Prototypes/Entities/Objects/Tools/emag.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/pka.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml, Resources/Prototypes/_EE/Entities/Objects/Weapons/Guns/SMGs/smgs.yml, Resources/Prototypes/_Goobstation/Entities/Weapons/Guns/Rifles/rifles.yml, Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Revolvers/revolvers.yml
убрал цветные описания с вещей антагов и оружия
=> [Remove] Conditional Desriptions On Antag Gear

Content.Server/VendingMachines/VendingMachineSystem.cs, Content.Shared/Interaction/SharedInteractionSystem.cs, Content.Shared/VendingMachines/VendingMachineComponent.cs, Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
+ фикс проверки коллизии
:cl: vanx
- fix: Наномед теперь выкидывает предметы с правильной стороны стены.
=> [Fix] Nano Med

Content.Shared/Climbing/Systems/ClimbSystem.cs, Resources/Prototypes/Entities/Structures/Holographic/projections.yml, Resources/Prototypes/Entities/Structures/Machines/Medical/biomass_reclaimer.yml, Resources/Prototypes/Entities/Structures/Machines/cloning_machine.yml, Resources/Prototypes/Entities/Structures/Machines/fax_machine.yml, Resources/Prototypes/Entities/Structures/Machines/medical_scanner.yml, Resources/Prototypes/Entities/Structures/Walls/railing.yml, Resources/Prototypes/Entities/Structures/cryopod.yml, Resources/Prototypes/Nyanotrasen/Entities/Structures/Machines/deep_fryer.yml, Resources/Prototypes/Nyanotrasen/Entities/Structures/Machines/laundry.yml, Resources/Prototypes/_Nuclear14/Entities/Structures/Furniture/barricades.yml, Resources/Prototypes/_Nuclear14/Entities/Structures/Furniture/table.yml
:cl: vanx
- fix: Залезание на стол больше не позволяет перелезать через все машины.
- tweak: Через некоторые машины теперь можно передвигаться залезнув на них или лёжа: капсула клонирования, медицинский сканер, фритюрница, переработчик биомассы, криопод, стиральная машина.
- add: Голобарьеры СБ и перила теперь можно сломать выстрелом.
=> [Fix] Climbing

Resources/Prototypes/Maps/Molecule.yml, Resources/Prototypes/Maps/anchor.yml, Resources/Prototypes/Maps/arena.yml, Resources/Prototypes/Maps/asterisk.yml, Resources/Prototypes/Maps/bagel.yml, Resources/Prototypes/Maps/cyberiad.yml, Resources/Prototypes/Maps/drydock.yml, Resources/Prototypes/Maps/gaxstation.yml, Resources/Prototypes/Maps/glacier.yml, Resources/Prototypes/Maps/hammurabi.yml, Resources/Prototypes/Maps/hive.yml, Resources/Prototypes/Maps/lambda.yml, Resources/Prototypes/Maps/lighthouse.yml, Resources/Prototypes/Maps/meta.yml, Resources/Prototypes/Maps/pebble.yml, Resources/Prototypes/Maps/radstation.yml, Resources/Prototypes/Maps/shoukou.yml, Resources/Prototypes/Maps/submarine.yml, Resources/Prototypes/Maps/tortuga.yml
=> [Fix] Map Job Tests

Resources/Prototypes/Entities/Objects/Specific/Hydroponics/tools.yml, Resources/Prototypes/Entities/Objects/Specific/Medical/surgery.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/HMGs/hmgs.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/LMGs/lmgs.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Launchers/launchers.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Rifles/rifles.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/pneumatic_cannon.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/cane.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/cult.yml, Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml, Resources/Prototypes/Nyanotrasen/Entities/Objects/Weapons/Melee/sword.yml, Resources/Prototypes/WhiteDream/Entities/Objects/Weapons/Melee/cult.yml, Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Melee/cane.yml, Resources/Prototypes/_White/Entities/Objects/Weapons/Melee/hosbat.yml
todo: добавить казнь выстрелом
:cl: vanx
- add: Больше ближнего оружия получило возможность казнить.
- remove: Убрана возможность казнить огнестрелом.
=> [Fix] Melee Executions

Content.Server/_White/TTS/TTSSystem.cs
:cl: vanx
- fix: Невербальные языки (например язык жестов) больше не озвучиваются ТТС.
- fix: ТТС больше не слышен глухим персонажам.
- fix: ТТС шёпота теперь слышен только с расстояния шёпота.
=> [Fix] Sign Language TTS

Resources/Prototypes/DeltaV/Roles/Jobs/Security/brigmedic.yml, Resources/Prototypes/Entities/Mobs/Cyborgs/borg_chassis.yml, Resources/Prototypes/Entities/Structures/Furniture/Tables/operating_table.yml, Resources/Prototypes/Entities/Structures/Furniture/beds.yml, Resources/Prototypes/GameRules/roundstart.yml, Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml, Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml, Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml, Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml, Resources/Prototypes/Roles/Jobs/Medical/senior_physician.yml, Resources/Prototypes/Traits/skills.yml, Resources/Prototypes/_Shitmed/Entities/Mobs/Player/abductor.yml, Resources/Prototypes/_Shitmed/Entities/Structures/Machines/autodoc.yml, Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml, Resources/Prototypes/_Shitmed/GameRules/events.yml, Resources/Prototypes/_White/GameRules/midround.yml
:cl: vanx
- tweak: Базовая скорость всех хирургических операций увеличена в 2 раза (x10 -> x5).
- tweak: Скорость операций хирургов (перк): х5, врачей, медборга и хирургической подготовки: х3, интернов: х2.
- add: Медик ядерных оперативников получил ускорение операций х5 (как у хирургов и абдукторов).
- add: Кровати теперь замедляют, операционный стол имеет коллизию. Теперь их можно сломать выстрелами, если навести курсор.
=> [Fix] Surgery Speed

Content.Server/Weapons/Ranged/Systems/GunSystem.AutoFire.cs, Content.Server/_White/Procedural/Systems/StartingAsteroidFieldSystem.cs, Directory.Build.props
=> [fix] [возможно, но не точно] a steroids

Content.Tools/test/0A.yml, Content.Tools/test/0B.yml, Content.Tools/test/0C.yml
=> hotfix resprite

Content.Tools/test/0A.yml, Content.Tools/test/0B.yml, Content.Tools/test/0C.yml, Resources/Prototypes/Tiles/floors.yml
no cl
FloorTechMaint2 и FloorTechMaint вернулись, спрайты сменились на deprecated.png
=> Respritefix1

Content.Server/Procedural/DungeonSystem.Rooms.cs, Content.Server/Procedural/RoomFillSystem.cs, Resources/Migrations/WWDPMigration.yml, Resources/Prototypes/Tiles/floors.yml
=> [Fix] Wonder Test

Resources/Prototypes/Entities/Objects/Materials/ore.yml
:cl: vanx
- tweak: Руды теперь переплавляются в ресурсы в соотношении 1 к 1, а не 1 к 5.
=> [Tweak] Ores 1984

Content.Server/_White/Lockers/StationAlertLevelLockSystem.cs, Content.Shared/Lock/LockSystem.cs, Content.Shared/_White/Lockers/SharedStationAlertLevelLockSystem.cs, Content.Shared/_White/Lockers/StationAlertLevelLockComponent.cs, Resources/Locale/en-US/_white/lockers/station-alert-level-lock.ftl, Resources/Locale/ru-RU/_white/lockers/station-alert-level-lock.ftl, Resources/Prototypes/Catalog/Fills/Lockers/security.yml, Resources/Prototypes/DeltaV/Catalog/Fills/Lockers/security.yml, Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/base_structurelockers.yml, Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml, Resources/Prototypes/Entities/Structures/Storage/glass_box.yml, Resources/Prototypes/_White/Entities/Structures/Storage/Closets/Lockers/lockers.yml
https://github.com/user-attachments/assets/96267d65-d958-4ecf-9536-757997ac0a25
:cl: vanx
- add: Кейс с антикварным лазером капитана и оружейные сейфы теперь открываются только при опасных кодах угрозы станции (красный и выше).
=> [Add] Alert Level Locks

Content.Client/_White/AntiParkinsons/AntiParkinsonsSystem.cs, Content.Server/_White/Procedural/Systems/StartingAsteroidFieldSystem.cs, Resources/Prototypes/_White/Ghosts/custom_ghosts.yml
=> [fix] Assteroids

Content.IntegrationTests/Tests/Body/LungTest.cs, Content.Server/Temperature/Systems/TemperatureSystem.cs, Resources/Prototypes/Entities/Clothing/Head/hardsuit-helmets.yml, Resources/Prototypes/Entities/Clothing/Head/helmets.yml, Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml, Resources/Prototypes/Entities/Mobs/NPCs/simplemob.yml, Resources/Prototypes/Entities/Mobs/Species/base.yml, Resources/Prototypes/Entities/Mobs/Species/shadowkin.yml, Resources/Prototypes/Entities/Mobs/base.yml
:cl: vanx
- add: Космические существа теперь не боятся температуры.
- fix: Скафандры снова защищают от температуры
- tweak: Комфортный лимит температуры тела уменьшен (+-10 -> +- 0.4 градуса).
=> [Fix] Temperature

Content.Server/Chat/Systems/ChatSystem.cs
Теперь игроки не смогут форматировать текст и баловаться в IC чате с надписями в духе
`>[bold][color=red]Я [color=orange]п[color=yellow]и[color=green]д[color=blue]о[color=purple]р`
No CL
=> [FIX] BBcode in IC

Resources/Prototypes/Entities/Objects/Fun/Instruments/instruments_structures.yml, Resources/Prototypes/Entities/Structures/Doors/Firelocks/firelock.yml, Resources/Prototypes/Entities/Structures/Doors/Windoors/base_structurewindoors.yml, Resources/Prototypes/Entities/Structures/Furniture/beds.yml, Resources/Prototypes/Entities/Structures/Furniture/chairs.yml, Resources/Prototypes/Entities/Structures/Lighting/base_lighting.yml, Resources/Prototypes/Entities/Structures/Machines/microwave.yml, Resources/Prototypes/Entities/Structures/Storage/Canisters/gas_canisters.yml, Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/base_structurelockers.yml, Resources/Prototypes/Entities/Structures/Storage/Closets/base_structureclosets.yml
:cl: Warete
- tweak: Изменён(скорректирован) структурный урон по объектам для правильной работы: пожарные шлюзы, раздвижные окна и прочие.
=> [Tweak] Another structure damage update

Resources/Prototypes/_White/Entities/Objects/Weapons/Guns/Projectiles/bolts.yml
:cl: vanx
- fix: Рентгеновская пушка теперь реально наносит урон сквозь стены
=> [Fix] Xray cannon

Resources/Prototypes/Tiles/floors.yml
=> [Fix] FloorTechMaint2

Resources/Prototypes/Tiles/floors.yml
no cl
попытка починить deprecated спрайты
=> мышка иди нахуй

Content.Server/Administration/Systems/AdminVerbSystem.Tools.cs, Content.Server/Administration/Systems/AdminVerbSystem.cs, Content.Shared/Mobs/Systems/MobStateSystem.Subscribers.cs
ТЕХНИЧЕСКИ, багом не считается, так как после восстановления здоровья, обычной медициной или через команду (Rejuvenate), у объекта обновляется состояние и собственно вызывается **UpdateCanMove**, а оттуда уже **_standing.Stand(target)**.
Ничего не ломается(вроде) и Космонавтик будет лежать дальше после лечение и не Отстёгиваться с тех кроватей/других объектов.
:cl: Warete
- tweak: Космонавтик после лечения больше  не будет автоматически вставать и слазать с кроватей.
=> [Fix/Tweak] "Heal no longer automatically stands you up"

Content.Client/Weapons/Ranged/Systems/GunSystem.Ballistic.cs, Content.Server/Weapons/Ranged/Systems/GunSystem.Ballistic.cs, Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.Ballistic.cs
Вновь на кнопочку Z достаются патроны и ватные палочки.
Ещё исправлен осмотр коробок/магазинов и их последнего объекта "поверх".
:cl: Warete
- fix: Из коробок/магазинов и ещё где это возможно, на клавишу Z вновь достаются предметы.
- fix: Исправлен осмотр коробок(последнего вложенного "поверх" объекта).
=> [Fix] Boxes/magazine's examine. And UseButton for extract.

Resources/Locale/ru-RU/chat/managers/chat-manager.ftl
https://discord.com/channels/1274951101464051846/1391618135794389113
---
:cl: Kutos
- fix: Приписка языка теперь отображается и в IC чате
=> [FIX] отображение языка в IC чате

Resources/Prototypes/Stacks/medical_stacks.yml
**Было 10 мази. Сколько?**
:cl: Warete
- fix: Мазь теперь стакается по 15.
=> [Fix] Ointment stack

Content.Shared/_White/Grab/GrabThrownSystem.cs
:cl: Kutos
- tweak: Теперь при столкновении предметов урон не может превышать 50 единиц.
=> [tweak] Костыль-фикс карпа

Resources/Locale/ru-RU/shuttles/emergency.ftl
В апстриме анонсам о прибытии шаттла эвакуации добавились новые переменные.
---
no cl
=> [Tweak] Update Ru Loc For Emergency Shuttle Announcement

Resources/Prototypes/Catalog/VendingMachines/Inventories/chefvend.yml, Resources/Prototypes/_White/Entities/Objects/Misc/landmines/ChemMine.yml
багфикс как багфикс че бубнетб
no cl
=> [FIX] плохой я тестировщик 

Resources/Prototypes/Nyanotrasen/Entities/Structures/Machines/deep_fryer.yml
Масло создаваемое в химии теперь может быть залито в фритюрницу
:cl: Aposto2 (Forg)
- fix: Масло из химии теперь работает, даёшь свой аналог KFC!
=> [FIX] Масло не масло

Resources/Prototypes/Entities/Mobs/Species/reptilian.yml
Это было сломано более 5-ти месяцев, странно что это заметили только сейчас. #762
---
:cl:
- fix: Ящеры теперь носят свои штаны нормально
=> [Fix] Lizard Displacements 

Content.Shared/_White/Guns/SharedGunFluxSystem.cs
=> god fucking damn it

Tools/actions_changelogs_since_last_run.py
=> [Feat] Discord Changelog Should Now Ping Roles

Content.Server/Atmos/EntitySystems/FlammableSystem.cs, Content.Server/EntityEffects/Effects/ExtinguishReaction.cs, Content.Server/EntityEffects/Effects/FlammableReaction.cs, Content.Server/_White/Procedural/Systems/StartingAsteroidFieldSystem.cs, Content.Shared/Movement/Pulling/Components/PullerComponent.cs, Content.Shared/Salvage/SharedSalvageSystem.Magnet.cs
Хотел больше фиксов сюда упаковать, но чёт не вышло.
фикс #729
Ещё должно было фиксить #734, но я слишком долго тупил и его пофиксили без меня :sob:
---
n/a
:cl:
- fix: Бесконечное горение людей при передаче стаков огня касанием.
=> The fixening

Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks.yml, Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/cake.yml, Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml, Resources/Prototypes/Reagents/Consumable/Drink/alcohol.yml, Resources/Prototypes/Reagents/Consumable/Drink/drinks.yml, Resources/Prototypes/Reagents/Consumable/Drink/soda.yml, Resources/Prototypes/Reagents/Consumable/Food/ingredients.yml, Resources/Prototypes/Reagents/toxins.yml
Перебалансировал вообще все напитки/еду которая может/не может содержать Теобромин и сделал более логичным (Там где шоколада много, его соответственно будет больше). 
---
Пустует..
:cl:
- add: Добавлен теобромин там где надо
- tweak: Изменено кол-во теобромина в разных напитках и еде
- remove: Удалён теобромин там где его быть не может
=> Make Theobromine gud (very gud)

Content.Server/Psionics/PsionicsSystem.cs, Resources/Prototypes/Psionics/PsionicPowerPool.yml, Resources/Prototypes/Psionics/psionics.yml
казино смягчено
потолок цены новой способности - 800
это всё работает
---
<p>
</p>
</details>
---
:cl:
- tweak: вес псионических сил равен
- tweak: максимум стоимость новой способности 800 потенции
=> psi-kasino nerf

.github/workflows/discord-changelog.yml
Титле ✓
---
:cl:
- fix: Дискорд Ченжлогер исправлен (наверное)
=> [Fix] Discord Changeloger

Content.Server/Ghost/GhostReturnToRoundSystem.cs, Resources/Locale/en-US/ghost/ghost-respawn.ftl
https://github.com/Simple-Station/Einstein-Engines/pull/2542
=> Tweak: Nerfed Juggernaut Ult (#2542)
