WWhiteDreamProject/wwdpublic

- Content.IntegrationTests/Pair/TestPair.Helpers.cs
- Content.IntegrationTests/PoolManager.cs
- Content.IntegrationTests/Tests/GameRules/AntagPreferenceTest.cs
- Content.IntegrationTests/Tests/GameRules/NukeOpsTest.cs
- Content.IntegrationTests/Tests/Interaction/Click/InteractionSystemTests.cs
- Content.IntegrationTests/Tests/ResettingEntitySystemTests.cs
- Content.Server/Administration/Systems/AdminVerbSystem.Antags.cs
- Content.Server/Antag/AntagSelectionSystem.API.cs
- Content.Server/Antag/AntagSelectionSystem.cs
- Content.Server/GameTicking/GameTicker.RoundFlow.cs
- Content.Server/GameTicking/Rules/SecretRuleSystem.cs
- Content.Server/Preferences/Managers/IServerPreferencesManager.cs
- Content.Server/Preferences/Managers/ServerPreferencesManager.cs
- Content.Shared/Antag/AntagAcceptability.cs
- Content.Shared/Roles/Jobs/SharedJobSystem.cs
- Content.Shared/Station/SharedStationSpawningSystem.cs
A bunch of fixes for recent antag refactor port from Wizden.
---
:cl:
- fix: Thieves and Ninjas now properly spawn with their gear / Ниндзя и воры теперь корректно спавнятся со своим снаряжением.
- fix Fixed MakeThief icon in admin verbs / Исправлена иконка MakeThief в педальной панели
> [Fix] Antags Refactor Fix

- Content.Client/Store/Ui/StoreMenu.xaml.cs
- Content.Server/Store/Systems/StoreSystem.Ui.cs
- Content.Server/Store/Systems/StoreSystem.cs
- Content.Server/_White/StoreDiscount/StoreDiscountSystem.cs
- Content.Shared/Store/ListingLocalisationHelpers.cs
- Content.Shared/Store/ListingPrototype.cs
- Content.Shared/Store/StorePresetPrototype.cs
- Content.Shared/_White/StoreDiscount/SalesSpecifier.cs
- Resources/Locale/en-US/_white/store/sales.ftl
- Resources/Locale/ru-RU/_white/store/sales.ftl
- Resources/Prototypes/Catalog/uplink_catalog.yml
- Resources/Prototypes/Store/presets.yml
- Resources/Prototypes/_White/Store/categories.yml
Порт скидок в аплинке.
---
:cl: Spatison
- add: Added discounts in uplink / Добавлены скидки в аплинк
> [Port]  Discounts In Uplink / Скидки В Аплинке

- Content.Shared/Weapons/Melee/MeleeWeaponComponent.cs
- Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs
- Resources/Prototypes/Entities/Objects/Fun/Instruments/instruments_string.yml
- Resources/Prototypes/Entities/Objects/Misc/briefcases.yml
- Resources/Prototypes/Entities/Objects/Misc/broken_bottle.yml
- Resources/Prototypes/Entities/Objects/Misc/fire_extinguisher.yml
- Resources/Prototypes/Entities/Objects/Specific/Chapel/bibles.yml
- Resources/Prototypes/Entities/Objects/Specific/Hydroponics/tools.yml
- Resources/Prototypes/Entities/Objects/Specific/Janitorial/janitor.yml
- Resources/Prototypes/Entities/Objects/Specific/Medical/surgery.yml
- Resources/Prototypes/Entities/Objects/Tools/gas_tanks.yml
- Resources/Prototypes/Entities/Objects/Tools/jaws_of_life.yml
- Resources/Prototypes/Entities/Objects/Tools/tools.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/baseball_bat.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/chainsaw.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/cult.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/fireaxe.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/home_run_bat.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/knife.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/mining.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/pickaxe.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/sledgehammer.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/spear.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/sword.yml
- Resources/Prototypes/Entities/Objects/Weapons/Melee/white_cane.yml
- Resources/Prototypes/Entities/Objects/Weapons/security.yml
Изменены параметры ближнего оружия:
- HeavyDamageBaseModifier: 1.2 => 1
---
:cl: Spatison
- add: Added disarm animation / Добавлена анимация толчка
- tweak: Heavy damage modifier: 1.2 => 1 /  Модификатор урона тяжелой атакой: 1
> [Tweak] Heavy Damage Modifier / Модификатор Урона Тяжелой Атакой

- Content.Shared/Throwing/ThrownItemComponent.cs
- Content.Shared/Throwing/ThrownItemSystem.cs
Исправление бага при котором брошенный предмет мог сработать на одну цель несколько раз.
---
:cl: Spatison
- fix: The trown item is now triggred once / Брошенные предметы теперь срабатывают единожды
> [Fix] Trown Item / Брошенный Предмет

- Content.IntegrationTests/Tests/DoAfter/DoAfterCancellationTests.cs
- Content.IntegrationTests/Tests/Interaction/InteractionTest.Helpers.cs
- Content.Shared/Prying/Components/PryingComponent.cs
- Content.Shared/Prying/Systems/PryingSystem.cs
- Content.Shared/Tools/Components/ToolTileCompatibleComponent.cs
- Resources/Locale/ru-RU/chat/managers/chat-manager.ftl
Если время взаимодействие с дверью ломом меньше 5 секунда, то дуафтер убирается. 
---
:cl: Spatison
- tweak: The duafter is removed when opening the door or tearing off the tile with a crowbar / Убран дуафтер при открывании шлюзов или отрывании плитки ломом
> [Tweak] Prying / Вскрытие

- Content.Shared/Inventory/InventorySystem.Equip.cs
- Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml
- Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
- Resources/Prototypes/Entities/Clothing/base_clothing.yml
- Resources/Prototypes/Entities/Objects/Devices/translators.yml
Описание. Хихи.
---
:cl:
- feat: Hardsuits now fit in backpacks / Скафандры теперь помещаются в рюкзаки.
- feat: Equip/Unequip do-afters no longer break on receiving damage / Процесс надевания/снимания одежды теперь не прерывается от получения урона.
- tweak: Most of the hardsuits slow down less now / Большая часть скафандром теперь слабее замедляет. 
- remove: Removed equip/unequip delay from most of the clothes / Убран ду-афтер одевания/снятия большей части одежды.
> [Tweak] Правки одежды

- Content.Server/GameTicking/GameTicker.Player.cs
- Content.Shared/Humanoid/Prototypes/SpeciesPrototype.cs
- Content.Shared/Preferences/HumanoidCharacterProfile.cs
- Resources/Locale/ru-RU/species/species.ftl
- Resources/Prototypes/Entities/Mobs/Species/arachnid.yml
- Resources/Prototypes/Entities/Mobs/Species/dwarf.yml
- Resources/Prototypes/Nyanotrasen/Species/Oni.yml
- Resources/Prototypes/Nyanotrasen/Species/felinid.yml
- Resources/Prototypes/Species/arachne.yml
- Resources/Prototypes/Species/dwarf.yml
- Resources/Prototypes/Species/harpy.yml
- Resources/Prototypes/Species/reptilian.yml
Описание.
---
:cl:
- add: Reintroduced dwarfs / Возвращены дворфы в игру. Лучше переносят алкоголь и имеют чуть больше выносливости, чем остальные расы.
- tweak: Arachnids now have action to place spider web and no longer slowed down by it / Арахниды получили возможность ставить паутину и не замедляться в ней.
- tweak: Most races min/max/default height and width was rebalanced. Now they go mostly +-10% from default / Параметры роста/ширины многих раз были изменены. Теперь они могут (в большинстве случаев) изменяться на максимум +-10% от стандартного значения.
- remove: Removed arachne from roundstart species pool / Арахне были удалены из стартового набора рас.
- remove: Removed oni from roundstart species pool / Они были удалены из стартового набора рас.
> [Feature] Minor races tweaks

- Content.Client/Silicons/Laws/Ui/LawDisplay.xaml.cs
- Content.Shared/Chat/SharedChatSystem.cs
- Content.Shared/Radio/EntitySystems/EncryptionKeySystem.cs
- Content.Shared/Radio/RadioChannelPrototype.cs
- Resources/Prototypes/DeltaV/radio_channels.yml
- Resources/Prototypes/radio_channels.yml
Описание.
---
---
:cl: Spatison
- add: Added ru keycodes / Добавлены русские ключи радиоканалов
> [Port] Ru Keycodes / Русские Ключи Радиоканалов

- Content.Server/_White/Melee/BackStab/BackStabComponent.cs
- Content.Server/_White/Melee/BackStab/BackStabSystem.cs
- Content.Server/_White/Melee/Crit/CritComponent.cs
- Content.Server/_White/Melee/Crit/CritSystem.cs
- Resources/Locale/en-US/_white/backstab/backstab.ftl
- Resources/Locale/en-US/_white/melee/backstab.ftl
- Resources/Locale/en-US/_white/melee/crit.ftl
- Resources/Locale/ru-RU/_white/backstab/backstab.ftl
- Resources/Locale/ru-RU/_white/melee/backstab.ftl
- Resources/Locale/ru-RU/_white/melee/crit.ftl
Переместил систему удара в спину на сервер. Добавил систему критического попадания для кровавого кинжала
> [Tweak] Melee / Ближнее Оружие

- Content.Shared/Localizations/ContentLocalizationManager.cs
- Content.Shared/_White/CVars.cs
Фикс не рабочего английского
---
no cl
> [Fix] Localizations / Локализация

- Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs
- Content.Server/Shuttles/Systems/ShuttleSystem.cs
При включенных магнитах теперь нельзя упасть при FTL перемещении. Вместо стана при FTL прыжке теперь просто падение. 
---
:cl: Spatison
- tweak: With FTL, a person now falls / При ФТЛ перемещении человек теперь падает
- tweak: Magnetic boots now do not let you fall / Магнитные сапоги теперь не дают упасть
> [Tweak] Magboots / Магнитные Сапоги

- Resources/Prototypes/DeltaV/NPC/roboisseur.yml
Уменьшена колизия у Бутлетрона
---
:cl: Spatison
- fix: Сorrection of a Butlutron collision / Исправлена коллизия Бутлетрона
> [Fix] Butletron / Бутлетрон

- Resources/Prototypes/secret_weights.yml
Изменены шансы выпадения режимов
:cl: Spatison
- tweak: Changed the chances of modes falling out / Изменены шансы выпадения режимов
> [Tweak] Secret / Секрет

- Resources/Prototypes/Entities/Objects/Weapons/Melee/pickaxe.yml
Кирка при тяжелом ударе теперь не тратит стамины, также скорость атаки и урон снижены
---
:cl: Spatison
- tweak: The pickaxe has been improved / Улучшена кирка
> [Tweak] Pickaxe / Кирка

- Content.Server/Holosign/HolosignProjectorComponent.cs
- Content.Server/Holosign/HolosignSystem.cs
- Content.Server/_White/Holosign/HolosignComponent.cs
- Content.Server/_White/Holosign/HolosignSystem.cs
- Resources/Locale/en-US/_white/holoprojector/holoprojector.ftl
- Resources/Locale/ru-RU/_white/holoprojector/holoprojector.ftl
- Resources/Migrations/migration.yml
- Resources/Prototypes/Entities/Objects/Devices/holoprojectors.yml
- Resources/Prototypes/Entities/Objects/Specific/Robotics/borg_modules.yml
- Resources/Prototypes/Entities/Structures/Holographic/projections.yml
- Resources/Prototypes/Nyanotrasen/Entities/Objects/Devices/holoprojectors.yml
- Resources/Prototypes/Recipes/Lathes/janitorial.yml
- Resources/Prototypes/Recipes/Lathes/security.yml
- Resources/Prototypes/Recipes/Lathes/tools.yml
Переработка голопроекторов, теперь они больше похоже на свой вариант из 13-ой станции.
---
:cl: Spatison
- tweak: The holoprojectors have been redesigned / Голопроекторы были переработаны
> [Tweak] Holoprojector / Голопроектрор

- Content.Server/Execution/ExecutionSystem.cs
Описание.
убийства
---
:cl: vanx
- add: Возвращена возможность казни
> Reenable Executions

- Content.Server/Chat/Systems/ChatSystem.cs
ТТС Теперь точно работает
---
no cl
> [Fix] TTS 

- Content.Shared/CombatMode/CombatModeComponent.cs
- Content.Shared/CombatMode/SharedCombatModeSystem.cs
- Content.Shared/MouseRotator/MouseRotatorComponent.cs
[smoothrot.webm](https://github.com/user-attachments/assets/9220cdad-9437-4bdb-8a80-25ca0b94cc23)
Чтобы выключить в прототипе:
`smoothRotation = false` в `CombatMode`. Дефолт пока что true.
:cl:
- add: В тестовом режиме: персонажи теперь вращаются на все полные, красивые 360°. Ну, кроме спрайтиков. Спрайтики всё ещё двухмерные, с четырьмя направлениями. Зато какие теперь классные фонарики!
> mom get the camera

- Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml
Агосты видят больше обычного
---
<p>
https://discord.com/channels/1274951101464051846/1310718412275716159
мед сб и диагностический визоры
самое сложное было сделать этот пр
</p>
</details>
---
- add: Aghosts with visors / Агосты с визорами
> [Feature] Aghosts with visors / Агосты с визорами

- Resources/Prototypes/Entities/Mobs/NPCs/xenopet.yml
Удалён ивент neutralXenoVents. Больше на станции не будет по 10 бесполезных тушек ксеносов.
---
:cl: Дексп
- remove: Удалён ивент neutralXenoVents
> Удалил ивент со спавном нейтральных ксеносов

- Resources/Prototypes/Catalog/VendingMachines/Inventories/medical.yml
- Resources/Prototypes/Catalog/VendingMachines/Inventories/medidrobe.yml
Обычные очки, медхуд и пиратская повязка на 1 глаз для врачей перенесены из НаноМед Плюс в МедШкаф
В МедШкаф добавлено 4 пояса врача
Описание.
---
<p>
https://discord.com/channels/1274951101464051846/1320186254092144683
</p>
</details>
---
- add: Пояс врача теперь в МедШкаф
- tweak: Очки, медхуд и повязка из НаноМед переехали в МедШкаф
> [Tweak] МедШкаф

- Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
Убрал решетки там где не надо, вернув недостающие, по итогам голосования  — 26.11.2024 5:15, доступы ( расширенные )
Добавляет ХоПу доступы, почти, во все углы станции. По итогам голосования  — 26.11.2024 5:15
---
:cl: ДикПикер
- tweak: Расширенные доступы ХоПа возвращены
> Вернул прежнее величие главе персонала №3

- Resources/Prototypes/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
- Resources/Prototypes/Entities/Structures/Piping/Atmospherics/special.yml
- Resources/Prototypes/Entities/Structures/Specific/Janitor/drain.yml
- Resources/Prototypes/_White/Recipes/Construction/Graphs/utilities/atmos_advanced.yml
- Resources/Prototypes/_White/Recipes/Crafting/utilities/atmos_advanced.yml
С голосовашек.
:cl:
- add: Added tiny fan & drain crafts. Be ware that disassembling them yields less resources than assembling | Добавлены крафты маленьких вентиляторов и дренажей. Учитывайте, что их разбор приносит меньше ресурсов, чем стоимость их сбора.
- remove: Most of the guns no longer require forced wielding. Rifles still can be wielded for increased accuracy. You can't wield SMGs though. | Большая часть оружия теперь не требует пренудительного держания в двух руках. Винтовки все еще можно взять в две руки, чтобы получить бонус к точности. ПП взять в две руки нельзя вовсе.
> [Feature] Changes From Discord Votes

- Resources/Prototypes/Entities/Objects/Devices/pda.yml
- Логика?
ПДА находится на поясе персонажа, следовательно, он должен светить прямо, а не как лампа вокруг.
- Что изменит?
Ты наконец-то будешь видеть в темноте куда именно ты утыкаешься, а не своего персонажа утыкающегося в темноту.
---
<p>
</p>
</details>
---
:cl: PuroSlavKing
- tweak: Changed PDA light, now it illuminates in front of you, not around / Изменен свет ПДА, теперь он освещает перед вами, а не вокруг вас.
> [Tweak] PDA Light

- Resources/Locale/ru-RU/prototypes/entities/objects/misc/tiles.ftl
- Resources/Prototypes/Entities/Objects/Misc/tiles.yml
Плитки пола больше не embeddable, потому что это было раздражающе да и выглядело крайне глупо.
---
:cl: vanx
- tweak: Летящие плитки пола больше не застревают в телах и стенах
> [Tweak] Flying tiles no longer embed on hit

- Resources/Prototypes/Entities/Objects/Weapons/security.yml
Исправление последствий непонятного нёрфа станбатонов - возможность сделать ОДИН удар в 3-4 секунды чувствуется просто отвратительно, из-за чего батон (особенно в харм режиме) невозможно юзать.
Вернул скорость атаки в 1 (чуть медленнее лома), уменьшил урон по стамине до 35 (для крита нужно 3 удара). 
В следствии увеличения необходимого кол-ва ударов на 50% поднял заряд до 15 ударов вместо 10.
---
:cl:
- tweak: Станбатон СБ теперь бьёт с обычной скоростью, но станит с трёх ударов.
> [Twe4k] Un-nerf stunb4ton 

- Resources/Prototypes/Maps/arena.yml
- Resources/Prototypes/Maps/asterisk.yml
- Resources/Prototypes/Maps/bagel.yml
- Resources/Prototypes/Maps/box.yml
- Resources/Prototypes/Maps/core.yml
- Resources/Prototypes/Maps/edge.yml
- Resources/Prototypes/Maps/europa.yml
- Resources/Prototypes/Maps/gaxstation.yml
- Resources/Prototypes/Maps/glacier.yml
- Resources/Prototypes/Maps/hammurabi.yml
- Resources/Prototypes/Maps/hive.yml
- Resources/Prototypes/Maps/lambda.yml
- Resources/Prototypes/Maps/lighthouse.yml
- Resources/Prototypes/Maps/meta.yml
- Resources/Prototypes/Maps/pebble.yml
- Resources/Prototypes/Maps/radstation.yml
- Resources/Prototypes/Maps/saltern.yml
- Resources/Prototypes/Maps/shoukou.yml
- Resources/Prototypes/Maps/submarine.yml
- Resources/Prototypes/Maps/tortuga.yml
Кол-во слотов на роли представителя НТ, магистрата и синего shitа установлено на 0. 
Роли не убраны чтобы на них действовала бюрократическая ошибка (и чтобы про них совсем не забыли).
Слоты можно добавить педалями вручную, используя команду `entities with StationJobs jobs:job NanotrasenRepresentative jobs:adjust 1`
---
:cl: vanx
- tweak: Убрана возможность раундстартом взять роли центрального командования и синего щита, просите педалей.
> [Twe4k] No roundst4rt CC roles

- Content.Shared/CCVar/CCVars.SoftCrit.cs
- Content.Shared/Mobs/Components/MobStateComponent.cs
- Content.Shared/Mobs/Systems/MobStateSystem.Subscribers.cs
- Resources/Prototypes/Entities/Mobs/Species/base.yml
Возвращает персонажам возможность ползать в критическом состоянии.
Теперь нельзя ползать, если персонажа держат-тащат.
---
:cl: vanx
- tweak: Персонажи снова могут ползать в крите
- tweak: Персонажи не могут ползать в крите если их схватить.
> [Tweak] Movement In Crit + No Breaking Pull

- Content.Server/IdentityManagement/IdentitySystem.cs
- Content.Server/_White/Examine/ExaminableCharacterComponent.cs
- Content.Server/_White/Examine/ExaminableCharacterSystem.cs
- Content.Shared/Hands/EntitySystems/SharedHandsSystem.Interactions.cs
- Content.Shared/Humanoid/SharedHumanoidAppearanceSystem.cs
- Resources/Locale/en-US/_white/examine/examine.ftl
- Resources/Locale/ru-RU/_white/examine/examine.ftl
- Resources/Prototypes/Entities/Mobs/Player/silicon_base.yml
- Resources/Prototypes/Entities/Mobs/Species/base.yml
Меняет описание в меню осмотра, добавляет список надетых вещей. 
Логирует список в чат игроку при включённой настройке.
---
---
:cl: vanx
- add: Добавлено отображение надетых вещей при осмотре и логирование в чат при включённой настройке.
> [Add] Better Character Examine

- Content.Server/Destructible/DestructibleSystem.cs
- Content.Shared/Projectiles/SharedProjectileSystem.cs
- Resources/Locale/en-US/weapons/throwing/throwing.ftl
- Resources/Locale/ru-RU/weapons/throwing/throwing.ftl
Застрявшие предметы теперь выпадают при разрушении или разборке.
Добавлена локализация.
---
:cl: vanx
- fix: Застрявшие предметы теперь выпадают при разрушении или разборке.
> [Fix] Embed Items Now Drop On Destruction/Deconstruction

- Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
Скорость лечения ран и ожогов хирургией уменьшена в 2 раза, восстанавливаемое здоровье увеличено в 2 раза - чтобы было меньше спама дуафтером.
Исправлены иконки необходимых инструментов.
---
> [Fix] Less Surgery Spam & Icon Fixes

- Content.Server/Weapons/Melee/MeleeWeaponSystem.cs
- Resources/Locale/ru-RU/damage/damage-examine.ftl
А вы знали что POWER ATTACK это ЛКМ ??? хахахахаха
---
---
:cl:
- fix: Исправлено отображение урона ближнего боя.
> [Fix] Melee Description Popup

- Resources/Maps/Moose.yml
- Resources/Maps/Salvage/DeltaV/DV-med-crashed-shuttle.yml
- Resources/Maps/Salvage/DeltaV/DV-med-library.yml
- Resources/Maps/Salvage/DeltaV/DV-tick-colony.yml
- Resources/Maps/Salvage/medium-crashed-shuttle.yml
- Resources/Maps/Salvage/medium-library.yml
- Resources/Maps/Salvage/tick-colony.yml
Сократить "exclamationmark" до "emark" я сократил, а вот переименовать все использования "exclamationmark" в картах в "emark" я забыл.
---
> decal rename fix

- Content.Shared/CCVar/CCVars.Interactions.cs
- Content.Shared/Movement/Systems/SharedMoverController.Input.cs
- Content.Shared/Movement/Systems/SharedMoverController.Relay.cs
Бег по дефолту в цварах.
InputRelay теперь корректно принимает изначальный бег/шаг и обновляет соответствующе.
---
:cl: vanx
- fix: Бег в мехах теперь работает по умолчанию и показывается на интерфейсе.
> [Fix] Input Relays Running State

- Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
- Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
Описание.
CL
---
(без движения/в движении)
---
:cl: vanx
- tweak: Теперь из дробовиков можно стрелять одной рукой с крайне низкой точностью
> [Tweak] Shotguns Requiring 2 Hands

- Resources/Prototypes/Nyanotrasen/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
Урон пистолета Universal: 35 -> 26
По аналогии с N1984, не затрагивает урон остальных пушек .45
:cl: vanx
- tweak: Урон пистолета Universal: 35 -> 26.
> [Tweak] .45 Pistol

- Resources/Prototypes/Nyanotrasen/GameRules/events.yml
- Resources/Prototypes/Psionics/psionics.yml
Теперь казино в псионике окупается
Ноосферный разряд ВРОДЕ КАК должен происходить чаще, но я не разбираюсь в этой штуке хелп
:cl:
- tweak: Событие Ноосферный разряд стало происходить чаще
- tweak: Шансы на получение улучшенной псионической способности стали лучше
- tweak: Минимум мерцания для появления ноосферных клещей уменьшено. 700 --> 600
> Minor psionics changes

- Content.Client/Entry/EntryPoint.cs
Добавил проверку на режим совместимости, если включен то выключается зернистость и всё, потому что весь экран становится белым и может отпугнуть некоторых игроков
---
<p>
</p>
</details>
---
:cl:
- fix: Зернистость сама отключается при включённом режиме совместимости
> [Fix] Выключение зернистости при включённом режиме совместимости

- Content.Server/GameTicking/Rules/DynamicRuleSystem.cs
- Resources/Prototypes/DeltaV/GameRules/midround.yml
- Resources/Prototypes/GameRules/dynamic_rules.yml
- Resources/Prototypes/GameRules/events.yml
- Resources/Prototypes/_Shitmed/GameRules/events.yml
Я написал свой метод распределения раундстартого бюджета, потому что у виздена... ЕГО НЕ БЫЛО. Смысл динамика в том, что он multiantag, при этом по их системе раундстартом спавнился всего один антаг. Хотя на самом деле они вообще не спавнились, потому что один из кондишенов для их спавна говорил им делать это до первой секунды запуска раунда, что невозможно из-за лагов.
Также были повышены цены некоторых ивентов. Отслеживать их можно здесь https://docs.google.com/spreadsheets/d/1_4ljuwgtKZTycCTxwcS8WFzesJgKfEQ52eNuEyi44K4/edit?usp=sharing
:cl:
- tweak: Повышены цены некоторых антагов в динамике. Их все также можно отслеживать в документе, ссылка на который приложена в PR.
- tweak: Добавлен минимальный порог игроков для спавна ниндзи и дракона.
- fix: Исправлен раундстартовый спавн антагов …
> Еще одна порция фиксов динамика

- Content.Server/Decals/DecalSystem.cs
- Content.Server/Procedural/DungeonSystem.Rooms.cs
- Resources/Maps/_White/Atlases/WonderBoxMaint.yml
Я наконец то разобрался с причиной по которой вондер бокс время от времени ломал тесты. На атласе было 2 несуществующих декаля. Во избежание повтора добавил логирование при попытке добавить несуществующий декаль.
---
no cl
> [Fix] Wonder Box Test Fail
